SELECT pg_temp.isolation_reject(format('INSERT INTO piggyvest_staging.provisioning_intents(goal_id) VALUES(%L)', :'canonical_goal'), '23514');
SELECT pg_temp.isolation_reject(format('INSERT INTO piggyvest_staging.wallet_goal_mappings(goal_id) VALUES(%L)', :'canonical_goal'), '23514');
SELECT pg_temp.isolation_reject(format('INSERT INTO piggyvest_goal_policy.lifecycle_activations(goal_id) VALUES(%L)', :'canonical_goal'), '23514');
SET LOCAL ROLE service_role;
SELECT pg_temp.isolation_reject(format('INSERT INTO piggyvest_staging.provisioning_intents(goal_id) VALUES(%L)', :'canonical_goal'), '42501');
SELECT pg_temp.isolation_reject(format('INSERT INTO piggyvest_staging.wallet_goal_mappings(goal_id) VALUES(%L)', :'canonical_goal'), '42501');
SELECT pg_temp.isolation_reject(format('INSERT INTO piggyvest_goal_policy.lifecycle_activations(goal_id) VALUES(%L)', :'canonical_goal'), '42501');
RESET ROLE;
SAVEPOINT disabled_drafts;
UPDATE savings_draft_private.settings SET enabled=false WHERE merchant_id=:'merchant';
SET SESSION AUTHORIZATION savings_local_plan_writer;
SELECT pg_temp.isolation_reject(format('SELECT pg_temp.insert_canonical(%L,%L)', :'second_canonical_goal', :'draft'), '42501');
RESET SESSION AUTHORIZATION;
ROLLBACK TO SAVEPOINT disabled_drafts;
SAVEPOINT disabled_terms;
UPDATE piggyvest_goal_policy.terms SET enabled=false
  WHERE version=(SELECT terms_version FROM public.customer_savings_drafts WHERE id=:'draft');
SET SESSION AUTHORIZATION savings_local_plan_writer;
SELECT pg_temp.isolation_reject(format('SELECT pg_temp.insert_canonical(%L,%L)', :'second_canonical_goal', :'draft'), '42501');
RESET SESSION AUTHORIZATION;
ROLLBACK TO SAVEPOINT disabled_terms;
SAVEPOINT elevated_login;
ALTER ROLE savings_local_plan_writer BYPASSRLS;
SET SESSION AUTHORIZATION savings_local_plan_writer;
SELECT pg_temp.isolation_reject(format('SELECT pg_temp.insert_canonical(%L,%L)', :'second_canonical_goal', :'draft'), '42501');
RESET SESSION AUTHORIZATION;
ROLLBACK TO SAVEPOINT elevated_login;
SAVEPOINT inherited_login;
GRANT authenticated TO savings_local_plan_writer;
SET SESSION AUTHORIZATION savings_local_plan_writer;
SELECT pg_temp.isolation_reject(format('SELECT pg_temp.insert_canonical(%L,%L)', :'second_canonical_goal', :'draft'), '42501');
RESET SESSION AUTHORIZATION;
ROLLBACK TO SAVEPOINT inherited_login;
