#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"

cd "$repo_root"

node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_sql_parser.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_nested_queries.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_availability.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_availability_narrowing.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_locks.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_branches.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_decrements.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_decrement_null_stock.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_decrement_guards.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_decrement_guards_branches.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_ddl.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_dynamic_ddl.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_dynamic_ddl_assignment.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_predicates.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_release.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_release_scope.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_review.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_claim.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_needed_count.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_claim_excess_release.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_claim_reachability.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_confirmation.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_confirmation_projection.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_confirmation_reachability.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_hold_eligibility.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_parser.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_roles.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_lifecycle.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_special_roles.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_execution.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_execution_lifecycle.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_execution_recreation.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_execution_session_scope.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privilege_execution_grant_scope.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_definition_patches.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_claim_shortage.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_confirmation_item_order.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privileges.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_privileges_release.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_claim_branches.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_confirmation_branches.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_public_wrappers.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_release_transitions.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_release_locks.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_sold_release.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_control_flow.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract_zero_row.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_contract.test.mjs"
node --test "$repo_root/supabase/tests/serialized_variant_inventory_concurrency_fixture_functions.test.mjs"
bash "$script_dir/apply-pending-migrations.test.sh"
node --test "$script_dir/repair-sales-migration-collision.test.mjs"
node --test "$script_dir/repair-sales-migration-collision.sql.test.mjs"
node --test "$script_dir/shipping-policy-audit-repair.test.mjs" "$script_dir/shipping-policy-audit-repair.sql.test.mjs"
node --test "$script_dir/checkout-reuse-ambiguous-id.sql.test.mjs"
bash "$script_dir/deferred-production-migrations.test.sh"
bash "$script_dir/apply-pending-migrations-version-collision.test.sh"
bash "$script_dir/historical-migration-repair-spec.test.sh"
bash "$script_dir/historical-migration-repair-backfill.test.sh"
bash "$repo_root/supabase/tests/run-serialized-variant-inventory-concurrency-test.sh"
bash "$repo_root/supabase/tests/run-storefront-order-private-schema-boundary-test.sh"
bash "$repo_root/supabase/tests/run-paystack-reference-claim-concurrency-test.sh"
bash "$repo_root/supabase/tests/run-merchant-invoice-partial-payment-review-index-test.sh"
bash "$repo_root/supabase/tests/run-gigl-tracking-retry-repair-test.sh"
bash "$repo_root/supabase/tests/run-gigl-monitor-backfill-repair-test-runner.test.sh"
bash "$repo_root/supabase/tests/run-gigl-monitor-backfill-repair-test.sh"
node --test "$script_dir/split-sql-statements.test.mjs"
