const providerEnvironmentKeys = [
  'BUILDER_AI_PROVIDER_BINDING_PEPPER',
  'CEREBRAS_API_KEY',
  'CEREBRAS_BUILDER_ACCOUNT_REF',
  'CEREBRAS_BUILDER_APPROVED_MODEL',
  'CEREBRAS_BUILDER_CREDENTIAL_BINDING_TAG',
  'CEREBRAS_BUILDER_DEPLOYMENT_TIER',
  'CEREBRAS_BUILDER_RELEASE_ATTESTED_AT',
  'GOOGLE_GENAI_API_KEY',
  'GOOGLE_BUILDER_ACCOUNT_REF',
  'GOOGLE_BUILDER_APPROVED_MODEL',
  'GOOGLE_BUILDER_CREDENTIAL_BINDING_TAG',
  'GOOGLE_BUILDER_DEPLOYMENT_TIER',
  'GOOGLE_BUILDER_RELEASE_ATTESTED_AT',
  'GROQ_API_KEY',
  'GROQ_BUILDER_ACCOUNT_REF',
  'GROQ_BUILDER_APPROVED_MODEL',
  'GROQ_BUILDER_CREDENTIAL_BINDING_TAG',
  'GROQ_BUILDER_DEPLOYMENT_TIER',
  'GROQ_BUILDER_RELEASE_ATTESTED_AT',
  'OPENROUTER_API_KEY',
  'OPENROUTER_BUILDER_TRANSPORT_APPROVED_AT',
  'OPENROUTER_BUILDER_TRANSPORT_APPROVED_MODEL',
] as const;

export function clearBuilderAiSmokeProviderEnvironment(
  environment: NodeJS.ProcessEnv = process.env
): void {
  for (const key of providerEnvironmentKeys) delete environment[key];
}
