#!/usr/bin/env bash
# Post-deploy .env reminder for VPS worker installs. Source this helper and
# call print_worker_env_reminder with REMOTE_DIR; kept out of deploy.sh so
# the deploy script stays under the 300-line modularization limit.

print_worker_env_reminder() {
  local remote_dir="${1:?REMOTE_DIR is required}"
  echo "    Reminder: create $remote_dir/.env if not already present:"
  echo "         NEXT_PUBLIC_SUPABASE_URL=..."
  echo "         NEXT_PUBLIC_SUPABASE_ANON_KEY=..."
  echo "         SUPABASE_SERVICE_ROLE_KEY=..."
  echo "         SUPABASE_JUMIA_CREDENTIAL_KEY=..."
  echo "         IMEI_IDENTIFIER_ENCRYPTION_KEY=..."
  echo "         PETROCK_API_TOKEN=..."
  echo "         PETROCK_API_BASE_URL=https://api.petrock.biz/api/reseller/v1"
  echo "         PETROCK_ENABLED=true"
  echo "         PETROCK_ENABLED_TIERS=..."
  echo "         PETROCK_REMEDIATION_ENABLED=true"
  echo "         QUIZ_PHASE=1a"
  echo "         QUIZ_PRODUCTION_APPROVED=false"
  echo "         QUIZ_RPC_SERVER_SECRET=..."
  echo "         QUIZ_DEVICE_HASH_PEPPER=..."
  echo "         BACI_REPO_DIR=/opt/baci/app  # object-source clone; deploy.sh manages per-SHA worktrees + the live symlink, never pull in place"
  echo "         GIGL_BASE_URL=..."
  echo "         GIGL_EMAIL=..."
  echo "         GIGL_PASSWORD=..."
  echo "         GIGL_TRACKING_WORKER_TOKEN=..."
  echo "         EXPO_ACCESS_TOKEN=...  # optional"
  echo "         JUMIA_CLIENT_ID=..."
  echo "         JUMIA_AUTHORIZATION_ENCRYPTION_KEY=..."
  echo "         BACI_WEB_BASE_URL=..."
  echo "         CRON_SECRET=..."
  echo "         VERCEL_ERROR_LOG_PATH=$remote_dir/logs/vercel-drain.jsonl"
  echo "         BACI_REMEDIATION_OUTPUT_DIR=$remote_dir/logs/vercel-error-remediator"
  echo "         BACI_SENTRY_REMEDIATION_OUTPUT_DIR=$remote_dir/logs/sentry-mobile-error-remediator"
  echo "         BACI_REMEDIATION_AUTOFIX_ENABLED=0"
  echo "         BACI_REMEDIATION_CANARY_ENABLED=1 # opt in to the daily no-change Codex canary"
  echo "         SENTRY_REMEDIATION_AUTH_TOKEN=... # dedicated token with event:read"
  echo "         SENTRY_ORG=..."
  echo "         SENTRY_PROJECT=..."
  echo "         VERCEL_LOG_DRAIN_SECRET=..."
  echo "         VERCEL_LOG_DRAIN_RECEIVER_PORT=8787"
  echo "         OLLAMA_STOREFRONT_BASE_URL=http://localhost:11434"
  echo "         AI_STOREFRONT_GENERATION_ENABLED=false"
  echo "         AI_STOREFRONT_TRIGGER_SECRET=..."
  echo "         AI_STOREFRONT_TRIGGER_HOST=127.0.0.1"
  echo "         AI_STOREFRONT_TRIGGER_PORT=3917"
  echo "         IMPORT_JOB_TRIGGER_SECRET=..."
  echo "         IMPORT_JOB_TRIGGER_HOST=127.0.0.1"
  echo "         IMPORT_JOB_TRIGGER_PORT=3918"
  echo "         EVENT_PIPELINE_ENQUEUE_ENABLED=false"
  echo "         EVENT_PIPELINE_ROUTING_MODE=disabled"
  echo "         EVENT_PIPELINE_ACTIVE_DESTINATIONS="
  echo "         EVENT_PIPELINE_CANARY_MERCHANT_IDS="
  echo "         EVENT_PIPELINE_DELIVERY_ENABLED=false"
  echo "         EVENT_PIPELINE_DISABLE_LEGACY_FANOUT=false"
  echo "         EVENT_PIPELINE_ALLOW_UNVERIFIED_TELEMETRY=false"
  echo "         EVENT_PIPELINE_MAX_DELIVERY_ATTEMPTS=8"
  echo "         EVENT_PIPELINE_DELIVERY_CONCURRENCY=5"
  echo "         EVENT_PIPELINE_INGRESS_MAX_READS=5"
  echo "         EVENT_DELIVERY_ATTEMPT_RETENTION=\"30 days\""
  echo "         EVENT_QUEUE_ARCHIVE_RETENTION=\"30 days\""
  echo "    Note: the storefront-update-nudge cron reads its config from the WEB"
  echo "          (Vercel) env, NOT this worker .env: MOBILE_STOREFRONT_UPDATES_ENABLED,"
  echo "          MOBILE_STOREFRONT_{ANDROID,IOS}_LATEST_BUILD and _STORE_URL, plus"
  echo "          optional MOBILE_STOREFRONT_UPDATE_MESSAGE (overrides the copy)."
  echo "          A missing LATEST_BUILD or _STORE_URL silently skips that platform."
}
