import { StyleSheet } from 'react-native';
import type { QuizThemeColors } from './QuizScreen.styles';

export function createQuizLeaderboardStyles(colors: QuizThemeColors) {
  return StyleSheet.create({
    screen: { backgroundColor: colors.background, flex: 1 },
    content: { gap: 12, padding: 20, paddingBottom: 40 },
    historyHeader: { gap: 8 },
    intro: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
    eventButton: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      gap: 3,
      padding: 15,
    },
    eventTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
    eventMeta: { color: colors.textSecondary, fontSize: 12 },
    boardHeader: { gap: 8, paddingBottom: 4 },
    backButton: { alignSelf: 'flex-start', paddingVertical: 4 },
    backButtonText: { color: colors.primary, fontSize: 14, fontWeight: '800' },
    selectedTitle: { color: colors.text, fontSize: 24, fontWeight: '900' },
    selectedMeta: { color: colors.textSecondary, fontSize: 13 },
    boardTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '900',
      marginTop: 8,
    },
    participantCount: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '800',
    },
    yourRankCard: {
      backgroundColor: colors.primaryLowOpacity,
      borderColor: colors.primary,
      borderRadius: 12,
      borderWidth: 1,
      gap: 2,
      marginTop: 4,
      padding: 12,
    },
    yourRankLabel: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 1,
    },
    yourRankValue: { color: colors.text, fontSize: 14, fontWeight: '800' },
    rankRow: {
      alignItems: 'center',
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 12,
      minHeight: 48,
      paddingVertical: 8,
    },
    podiumRow: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      marginVertical: 2,
      paddingHorizontal: 10,
    },
    podiumRank: {
      backgroundColor: colors.primaryLowOpacity,
      borderRadius: 8,
      paddingVertical: 4,
      textAlign: 'center',
      width: 42,
    },
    currentRankRow: {
      backgroundColor: colors.primaryLowOpacity,
      borderRadius: 10,
      paddingHorizontal: 10,
    },
    rank: { color: colors.primary, fontSize: 16, fontWeight: '900', width: 34 },
    identity: { flex: 1, gap: 2 },
    name: { color: colors.text, fontSize: 14, fontWeight: '700' },
    time: {
      color: colors.textSecondary,
      fontSize: 12,
      fontVariant: ['tabular-nums'],
      fontWeight: '600',
    },
    score: { color: colors.textSecondary, fontSize: 13, fontWeight: '700' },
    state: {
      color: colors.textSecondary,
      fontSize: 14,
      paddingVertical: 24,
      textAlign: 'center',
    },
    error: {
      color: colors.error,
      fontSize: 14,
      paddingVertical: 20,
      textAlign: 'center',
    },
  });
}
