import { StyleSheet } from 'react-native';
import type { QuizThemeColors } from './QuizScreen.styles';

export function createQuizLobbyStyles(colors: QuizThemeColors) {
  return StyleSheet.create({
    eventsList: { flex: 1, overflow: 'hidden' },
    eventsListContent: { gap: 16, padding: 20, paddingBottom: 40 },
    patternBackground: {
      bottom: 0,
      left: 0,
      pointerEvents: 'none',
      position: 'absolute',
      right: 0,
      top: 0,
    },
    emptyState: {
      alignItems: 'center',
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      gap: 6,
      padding: 24,
    },
    emptyStateTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '800',
      textAlign: 'center',
    },
    emptyStateText: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
    },
    eventCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      gap: 14,
      overflow: 'hidden',
      padding: 18,
    },
    eventCardClosed: { backgroundColor: colors.muted },
    eventTopline: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    prizeMoment: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
    },
    liveBadge: {
      backgroundColor: '#DA2C38',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    testBadge: {
      backgroundColor: '#344054',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    badgeText: {
      color: '#FFF',
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 1,
    },
    prizeStage: { alignItems: 'center', flexDirection: 'row', minHeight: 156 },
    prizeCopy: { flex: 1, gap: 8, zIndex: 1 },
    prizeImageFrame: {
      alignItems: 'center',
      height: 156,
      justifyContent: 'center',
      marginLeft: -10,
      width: 132,
    },
    prizeImage: { height: 150, transform: [{ rotate: '9deg' }], width: 125 },
    eventTitle: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
    },
    eventPrize: {
      color: colors.text,
      fontSize: 27,
      fontWeight: '900',
      letterSpacing: -0.7,
    },
    prizeCondition: {
      alignSelf: 'flex-start',
      backgroundColor: colors.primaryLowOpacity,
      borderRadius: 999,
      color: colors.primary,
      fontSize: 12,
      fontWeight: '800',
      overflow: 'hidden',
      paddingHorizontal: 9,
      paddingVertical: 5,
      textTransform: 'capitalize',
    },
    countdownRow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
    livePulse: {
      backgroundColor: '#DA2C38',
      borderRadius: 5,
      height: 8,
      width: 8,
    },
    countdownValue: {
      color: colors.text,
      fontSize: 22,
      fontVariant: ['tabular-nums'],
      fontWeight: '900',
    },
    countdownLabel: { color: colors.textSecondary, fontSize: 13 },
    timingStrip: {
      alignItems: 'center',
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      borderTopColor: colors.border,
      borderTopWidth: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
      paddingVertical: 12,
    },
    timingFact: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    timingDot: { color: colors.muted },
    primaryButtonBox: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      overflow: 'hidden',
    },
    disabledButtonBox: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      overflow: 'hidden',
    },
    primaryButton: {
      alignItems: 'center',
      borderRadius: 14,
      justifyContent: 'center',
      minHeight: 50,
      paddingHorizontal: 16,
    },
    primaryButtonText: {
      color: colors.primaryForeground,
      fontSize: 16,
      fontWeight: '800',
    },
    disabledButtonText: {
      color: colors.textSecondary,
      fontSize: 16,
      fontWeight: '800',
    },
    everySecond: {
      color: colors.textSecondary,
      fontSize: 12,
      textAlign: 'center',
    },
    rulesLink: {
      alignItems: 'center',
      alignSelf: 'center',
      flexDirection: 'row',
      gap: 5,
      padding: 4,
    },
    rulesLinkText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
    },
    modalBackdrop: {
      backgroundColor: 'rgba(0,0,0,0.72)',
      flex: 1,
      justifyContent: 'flex-end',
    },
    rulesSheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      gap: 22,
      padding: 24,
      paddingBottom: 36,
    },
    rulesHeader: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    rulesTitle: { color: colors.text, fontSize: 24, fontWeight: '900' },
    rulesEvent: { color: colors.textSecondary, fontSize: 13, marginTop: 3 },
    rulesList: { gap: 13 },
    ruleText: { color: colors.textSecondary, fontSize: 15, lineHeight: 22 },
    termsRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 10 },
    termsText: {
      color: colors.textSecondary,
      flex: 1,
      fontSize: 14,
      lineHeight: 20,
    },
    termsLink: {
      color: colors.primary,
      fontWeight: '800',
      textDecorationLine: 'underline',
    },
    rulesActionBox: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      overflow: 'hidden',
    },
  });
}
