import { expect, it } from 'vitest';

import { isNeverMatchingMediaQuery } from './review-handoff-media-query';

it.each([
  'not all',
  'NOT ALL',
  '  not   all  ',
  '(',
  ')',
  '((min-width: 1px)',
  '(min-width: 1px))',
  '()',
  '(   )',
  '"(min-width: 1px)',
  '[color]',
  'not all, (',
  '(, [x]',
  '(, screen',
  '(max-width: -1px)',
  '(MAX-WIDTH: -1PX)',
  '(width: -0.5px)',
  '(width < 0px)',
  '(width <= -1px)',
  '(100px > width > 400px)',
  '(100px < width < 50px)',
  'screen and (max-width: -1px)',
  '(max-width: -1px) and (color)',
  '(max-width: -1px) or (max-height: -1px)',
  'not (min-width: -1px)',
  '((max-width: -1px))',
  '(1in <= width <= 10px)',
  '(10px >= width >= 1in)',
  '(100px < width < 1in)',
  '(1in < width < 96px)',
  '(2.54cm <= width <= 95px)',
  '(72pt <= height <= 50px)',
  'not all/*',
  'not all/* unclosed trailing text',
  '(max-width: -1px)/*',
])('detects a never-matching media value: %s', (value) => {
  expect(isNeverMatchingMediaQuery(value)).toBe(true);
});

it.each([
  '',
  '   ',
  ',',
  'screen',
  'all',
  '(min-width: 100px)',
  '((min-width: 100px))',
  'screen and (color)',
  'not all, screen',
  '), screen',
  '(orientation: "(")',
  'not screen',
  '(min-width: -1px)',
  '(width >= -1px)',
  '(MIN-WIDTH: 0px)',
  '(width > 100px)',
  '(400px > width > 100px)',
  '(400px <= width <= 800px)',
  '(width <= 0px)',
  '(min-width: 100px)',
  '(max-width: 100px)',
  '(orientation: landscape)',
  '(max-width: -1px) or (color)',
  'not (max-width: -1px)',
  '(96px <= width <= 1in)',
  '(10px <= width <= 1in)',
  '(1in <= width <= 200px)',
  '(50vw <= width <= 100px)',
  '(10em <= width <= 5px)',
  'screen/*unclosed',
  '/* unclosed leading everything',
  'screen/*closed*/ and (color)',
])('keeps a possibly-matching media value applicable: %s', (value) => {
  expect(isNeverMatchingMediaQuery(value)).toBe(false);
});
