import type { Control, FieldErrors } from 'react-hook-form';
import type { CheckoutDeliveryCardProps } from '@/components/checkout/CheckoutDeliveryCard.types';
import type Colors from '@/constants/Colors';
import type { SavedAddress } from '@/lib/checkout-saved-address';
import type { ShippingAddressInput } from '@/lib/validation';
import type { MerchantPickupLocation } from './merchant-pickup-location';
import type { DeliveryMethod, ShippingQuote } from './types';

type ColorsScheme = (typeof Colors)['light'];

export interface CheckoutAddressStepViewProps {
  accountPassword: string;
  colors: ColorsScheme;
  contactSummary: string;
  control: Control<ShippingAddressInput>;
  currentDeliverySummary: string;
  defaultSavedAddress: SavedAddress | null;
  deliveryMethod: DeliveryMethod;
  errors: FieldErrors<ShippingAddressInput>;
  formContentPaddingBottom: number;
  hasContactIdentity: boolean;
  hasSavedAddresses: boolean;
  isAddingNewAddress: boolean;
  isAuthenticated: boolean;
  isContactCollapsed: boolean;
  isDark: boolean;
  isDeliveryCollapsed: boolean;
  isLoadingCities: boolean;
  isLoadingLocations: boolean;
  isLoadingQuotes: boolean;
  isLoadingSavedAddresses: boolean;
  showLocationPickers: boolean;
  merchantPickupLocation?: MerchantPickupLocation;
  onAddressSelected: CheckoutDeliveryCardProps['onAddressSelected'];
  onAddressTextChanged: CheckoutDeliveryCardProps['onAddressTextChanged'];
  onChangeAccountPassword: (value: string) => void;
  onContactEmailSettled: () => void;
  onOpenCityPicker: () => void;
  onOpenNewAddressEditor: () => void;
  onOpenStatePicker: () => void;
  onRetryQuotes: () => void;
  onSelectDeliveryMethod: (method: DeliveryMethod) => void;
  onSelectQuote: (quoteId: string) => void;
  onToggleContactCollapsed: () => void;
  onToggleDeliveryCollapsed: () => void;
  onToggleSaveAsDefaultAddress: () => void;
  onToggleSaveDetails: () => void;
  onUseSavedAddress: CheckoutDeliveryCardProps['onUseSavedAddress'];
  phone: string;
  saveAsDefaultAddress: boolean;
  saveDetails: boolean;
  savedAddresses: SavedAddress[];
  selectedQuote: ShippingQuote | undefined;
  selectedQuoteId: string;
  selectedSavedAddress: SavedAddress | null;
  selectedSavedAddressId: string | null;
  shippingQuotes: ShippingQuote[];
  watchedCity: string;
  watchedEmail: string;
  watchedState: string;
}
