export const paidInterestFixture = {
  config: {
    integrationId: '00000000-0000-4000-8000-000000000004',
    environment: 'production' as const,
    businessId: 'fixture-business',
    providerToken: 'test-only-provider-token',
    webhookSecret: 'test-only-signing-secret',
    retainedWebhookSecrets: [],
    database: {
      host: 'db.example.com',
      port: 5432,
      name: 'postgres',
      login: 'baci_piggyvest_primary_evidence',
      password: 'test-only-db-password',
      certificateAuthority: 'test-only-ca',
    },
  },
  event: {
    eventId: 'paid-event',
    eventType: 'interest-payout.success',
    eventCategory: 'interest-payout',
    customer_id: 'webhook-customer',
    eventData: {
      id: 'provider-payout',
      amount: 3000,
      destination_wallet: 'internal-destination',
      destination_wallet_balance: 13000,
      destination_wallet_ledger_balance: 13000,
      reference: 'paid-reference',
      timestamp: '2026-10-07T20:00:00.000Z',
      batch_id: 'batch',
      break_down: {
        gross_interest_payout: 3158,
        withholding_tax: 158,
        net_interest_payout: 3000,
      },
    },
    pvb_reference: 'paid-envelope-reference',
    pvb_wallet: 'source-interest-wallet',
    pvb_accrued_interest_wallet: 'accrued-interest-wallet',
    pvb_destination_wallet: null,
    pvb_third_party_reference: null,
  },
  crosswalk: {
    id: '00000000-0000-4000-8000-000000000099',
    integrationId: '00000000-0000-4000-8000-000000000004',
    environment: 'production' as const,
    businessId: 'fixture-business',
    apiWalletId: 'exact-api-wallet-with-hyphens',
    apiCustomerId: 'api-customer',
    webhookCustomerId: 'webhook-customer',
    sourceWalletId: 'source-interest-wallet',
    accruedWalletId: 'accrued-interest-wallet',
    destinationWalletId: 'internal-destination',
    envelopeDestinationWalletId: null,
    providerEvidenceSha256: 'a'.repeat(64),
    policyReference: 'fixture-approved-net-policy',
  },
  wallet: {
    status: true as const,
    data: {
      id: 'exact-api-wallet-with-hyphens',
      api_customer_id: 'api-customer',
      business_id: 'fixture-business',
      currency: 'NGN',
      balance: 13000,
      status: 'active',
    },
  },
};
