import { primaryWalletCardCheckoutFixture as checkout } from './primary-wallet-card-checkout.test-fixture';

const context = {
  operationId: checkout.intent.operationId,
  integrationId: checkout.settings.integrationId,
  merchantId: checkout.settings.merchantId,
  customerId: checkout.intent.customerId,
  environment: 'staging',
  businessId: checkout.settings.businessId,
  amountKobo: 25000,
  sourceWalletId: 'owner-treasury',
  destinationWalletId: checkout.intent.destinationWalletId,
  destinationCustomerId: checkout.intent.destinationCustomerId,
  reference: `pvb-primary-transfer-${checkout.intent.operationId}`,
} as const;
const now = Date.parse('2026-10-07T20:00:00Z');

export const primaryCardCustodyFixture = {
  now,
  context,
  configuration: {
    integrationId: context.integrationId,
    merchantId: context.merchantId,
    businessId: context.businessId,
    crosswalkAuthority: {
      contractId: 'mock-approved-contract',
      evidenceIssuer: 'mock-approved-issuer',
      treasuryWebhookCustomerId: context.businessId,
      transactionCustomerId: context.businessId,
    },
    environment: 'staging',
    expiresAt: checkout.settings.expiresAt,
    apiToken: 'mock-api-only',
    webhookSecret: 'mock-hmac-only',
    transfer: { ...checkout.database, login: 'baci_primary_card_transfer' },
    custody: { ...checkout.database, login: 'baci_primary_card_custody' },
  },
  envelope: {
    eventId: 'internal-event',
    eventType: 'wallet-transfer.outflow.success',
    eventCategory: 'wallet-transfer',
    customer_id: context.businessId,
    pvb_wallet: context.sourceWalletId,
    pvb_reference: 'canonical-transfer',
    pvb_destination_wallet: context.destinationWalletId,
    eventData: {
      amount: 25000,
      currency: 'NGN',
      transaction_id: 'canonical-transfer',
    },
  },
  single: {
    status: true,
    data: {
      id: 'canonical-transfer',
      customer_id: context.businessId,
      source_wallet: context.sourceWalletId,
      destination_wallet: context.destinationWalletId,
      reference: 'provider-reference',
      third_party_reference: context.reference,
      internal_reference: 'canonical-transfer',
      category: 'wallet_transfer',
      status: 'successful',
      amount: 25000,
      fee: 0,
    },
  },
  verification: {
    status: true,
    data: { reference: context.reference, status: 'success', amount: 25000 },
  },
  sourceWallet: {
    status: true,
    data: {
      id: context.sourceWalletId,
      business_id: context.businessId,
      currency: 'NGN',
      balance: 1000000,
      status: 'active',
    },
  },
  destinationWallet: {
    status: true,
    data: {
      id: context.destinationWalletId,
      business_id: context.businessId,
      api_customer_id: 'api-customer',
      currency: 'NGN',
      balance: 25000,
      status: 'active',
    },
  },
  crosswalk: {
    authority: 'provider_authenticated_crosswalk',
    contractId: 'mock-approved-contract',
    evidenceIssuer: 'mock-approved-issuer',
    treasuryWebhookCustomerId: context.businessId,
    transactionCustomerId: context.businessId,
    integrationId: context.integrationId,
    merchantId: context.merchantId,
    customerId: context.customerId,
    businessId: context.businessId,
    publicWalletId: context.destinationWalletId,
    apiCustomerId: 'api-customer',
    webhookCustomerId: context.destinationCustomerId,
    canonicalTransactionId: 'canonical-transfer',
    bankInflowTransactionId: 'bank-transfer',
    aliasesComplete: true,
    transactionAliases: ['canonical-transfer', 'bank-transfer'],
    evidenceSha256: 'b'.repeat(64),
    observedAt: '2026-10-07T19:59:59Z',
    expiresAt: '2026-10-07T20:00:30Z',
  },
  bodyDigest: 'a'.repeat(64),
} as const;
