import { OrderShipmentBookingError } from './order-shipment-booking-utils';

const RELEASEABLE_BOOKING_ERROR_CODES = new Set([
  'ORDER_NOT_FOUND',
  'MISSING_SHIPPING_QUOTE',
  'INVALID_SHIPPING_PROVIDER',
  'MISSING_ORDER_ITEMS',
  'QUOTE_NOT_FOUND',
  'QUOTE_ORDER_MISMATCH',
  'QUOTE_METADATA_LOOKUP_FAILED',
  'QUOTE_REFRESH_ORDER_UPDATE_FAILED',
  'QUOTE_REFRESH_UNAVAILABLE',
  'QUOTE_REFRESH_FAILED',
  'QUOTE_REFRESH_PERSIST_FAILED',
  'MERCHANT_WALLET_QUOTE_RECONFIRM_REQUIRED',
  'MERCHANT_WALLET_INSUFFICIENT',
  'QUOTE_PRICE_CHANGED',
  'MERCHANT_NOT_FOUND',
  'MERCHANT_LOOKUP_FAILED',
  'MERCHANT_SENDER_REQUIRED',
  'MERCHANT_ORIGIN_MISSING',
  'INCOMPLETE_SHIPPING_ADDRESS',
  'INTERNATIONAL_QUOTE_REQUEST_MISSING',
  'INTERNATIONAL_QUOTE_SENDER_MISSING',
  'INTERNATIONAL_QUOTE_ORDER_MISMATCH',
  'SHIPPING_QUOTE_RECEIVER_MISMATCH',
  'SHIPPING_QUOTE_ITEMS_MISMATCH',
  'MERCHANT_WALLET_CHARGE_REFUNDED',
  'MERCHANT_WALLET_BOOKED_SHIPMENT_MISSING',
  'INTERNATIONAL_QUOTE_ITEM_METADATA_MISMATCH',
  'GIGL_INTERNATIONAL_COUNTRY_LOOKUP_FAILED',
  'GIGL_INTERNATIONAL_DESTINATION_COUNTRY_NOT_FOUND',
  'GIGL_INTERNATIONAL_ITEM_HS_CODE_MISSING',
  'GIGL_INTERNATIONAL_ITEM_PACKAGE_LIMIT',
  'GIGL_INTERNATIONAL_SHIPMENT_PACKAGE_LIMIT',
  'GIGL_INTERNATIONAL_RATE_INVALID',
  'GIGL_BOOKING_VALIDATION_FAILED',
  'GIGL_AUTHENTICATION_FAILED',
  'GIGL_STATION_RESOLUTION_FAILED',
  'SHIPPING_PROVIDER_DISABLED',
  'EXISTING_SHIPMENT_LOOKUP_FAILED',
  'INCOMPLETE_EXISTING_SHIPMENT',
  'EXISTING_SHIPMENT_PROVIDER_MISMATCH',
  'EXISTING_SHIPMENT_QUOTE_MISMATCH',
]);

export function shouldReleaseBookingLock(
  error: unknown
): error is OrderShipmentBookingError {
  return (
    error instanceof OrderShipmentBookingError &&
    RELEASEABLE_BOOKING_ERROR_CODES.has(error.code)
  );
}
