export type MobileAdEnvironment = Readonly<Record<string, string | undefined>>;

/**
 * Default environment snapshot. Every variable is read with static
 * `process.env.EXPO_PUBLIC_*` dot notation because Expo only inlines
 * statically referenced variables into release bundles — computed
 * `process.env[key]` reads stay undefined in production and would disable
 * every placement (or throw for uncaught callers). Callers that need a
 * synthetic environment (tests, previews) pass `options.environment`.
 *
 * When adding a placement, add its variables here AND to
 * MOBILE_AD_ENV_KEYS (covered by `mobile-ad-environment.test.ts`).
 */
export function readMobileAdDefaultEnvironment(): MobileAdEnvironment {
  return {
    EXPO_PUBLIC_MOBILE_ADS_ENABLED: process.env.EXPO_PUBLIC_MOBILE_ADS_ENABLED,
    EXPO_PUBLIC_ADMOB_ANDROID_HOME_STRIP_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_HOME_STRIP_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_HOME_STRIP_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_HOME_STRIP_UNIT_ID,
    EXPO_PUBLIC_ADMOB_ANDROID_PRODUCT_GRID_IN_FEED_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_PRODUCT_GRID_IN_FEED_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_PRODUCT_GRID_IN_FEED_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_PRODUCT_GRID_IN_FEED_UNIT_ID,
    EXPO_PUBLIC_ADMOB_ANDROID_PRODUCT_GRID_MPU_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_PRODUCT_GRID_MPU_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_PRODUCT_GRID_MPU_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_PRODUCT_GRID_MPU_UNIT_ID,
    EXPO_PUBLIC_ADMOB_ANDROID_CART_MPU_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_CART_MPU_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_CART_MPU_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_CART_MPU_UNIT_ID,
    EXPO_PUBLIC_ADMOB_ANDROID_ORDER_SUCCESS_BANNER_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_ORDER_SUCCESS_BANNER_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_ORDER_SUCCESS_BANNER_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_ORDER_SUCCESS_BANNER_UNIT_ID,
    EXPO_PUBLIC_ADMOB_ANDROID_FOOTER_ANCHOR_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_FOOTER_ANCHOR_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_FOOTER_ANCHOR_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_FOOTER_ANCHOR_UNIT_ID,
    EXPO_PUBLIC_ADMOB_ANDROID_POST_ORDER_INTERSTITIAL_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_POST_ORDER_INTERSTITIAL_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_POST_ORDER_INTERSTITIAL_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_POST_ORDER_INTERSTITIAL_UNIT_ID,
    EXPO_PUBLIC_ADMOB_ANDROID_QUIZ_START_INTERSTITIAL_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_ANDROID_QUIZ_START_INTERSTITIAL_UNIT_ID,
    EXPO_PUBLIC_ADMOB_IOS_QUIZ_START_INTERSTITIAL_UNIT_ID:
      process.env.EXPO_PUBLIC_ADMOB_IOS_QUIZ_START_INTERSTITIAL_UNIT_ID,
    EXPO_PUBLIC_QUIZ_ADMOB_ANDROID_REWARDED_UNIT_ID:
      process.env.EXPO_PUBLIC_QUIZ_ADMOB_ANDROID_REWARDED_UNIT_ID,
    EXPO_PUBLIC_QUIZ_ADMOB_IOS_REWARDED_UNIT_ID:
      process.env.EXPO_PUBLIC_QUIZ_ADMOB_IOS_REWARDED_UNIT_ID,
  };
}
