export const builderPreviewThemeStaticShape = {
  animations: {
    duration: { fast: 'text', normal: 'text', slow: 'text' },
    easing: {
      easeIn: 'text',
      easeInOut: 'text',
      easeOut: 'text',
      linear: 'text',
    },
  },
  borders: {
    radius: {
      '2xl': 'text',
      full: 'text',
      lg: 'text',
      md: 'text',
      none: 'text',
      sm: 'text',
      xl: 'text',
    },
    style: { dashed: 'text', dotted: 'text', solid: 'text' },
    width: { none: 'text', normal: 'text', thick: 'text', thin: 'text' },
  },
  colors: {
    border: 'text',
    muted: 'text',
    mutedForeground: 'text',
    button: {
      accent: { background: 'text', hover: 'text', text: 'text' },
      primary: { background: 'text', hover: 'text', text: 'text' },
      secondary: { background: 'text', hover: 'text', text: 'text' },
    },
    card: { background: 'text', border: 'text', text: 'text' },
    footer: {
      background: 'text',
      linkColor: 'text',
      linkHoverColor: 'text',
      text: 'text',
    },
    header: {
      background: 'text',
      iconColor: 'text',
      searchBackground: 'text',
      searchBorder: 'text',
      text: 'text',
    },
    input: {
      background: 'text',
      border: 'text',
      focusBorder: 'text',
      placeholder: 'text',
      text: 'text',
    },
  },
  layout: {
    breakpoints: {
      '2xl': 'text',
      lg: 'text',
      md: 'text',
      sm: 'text',
      xl: 'text',
    },
    zIndex: {
      dropdown: 'number',
      fixed: 'number',
      modal: 'number',
      modalBackdrop: 'number',
      popover: 'number',
      sticky: 'number',
      tooltip: 'number',
    },
  },
  shadows: {
    '2xl': 'text',
    inner: 'text',
    lg: 'text',
    md: 'text',
    none: 'text',
    sm: 'text',
    xl: 'text',
  },
  spacing: {
    '2xl': 'text',
    '3xl': 'text',
    lg: 'text',
    md: 'text',
    sm: 'text',
    xl: 'text',
    xs: 'text',
    container: { maxWidth: 'text', paddingX: 'text' },
    footer: { paddingX: 'text', paddingY: 'text' },
    header: { height: 'text', paddingX: 'text', paddingY: 'text' },
    section: { paddingX: 'text', paddingY: 'text' },
  },
  typography: {
    fontFamily: { body: 'text', heading: 'text', mono: 'text' },
    fontSize: {
      '2xl': 'text',
      '3xl': 'text',
      '4xl': 'text',
      '5xl': 'text',
      '6xl': 'text',
      base: 'text',
      lg: 'text',
      sm: 'text',
      xl: 'text',
      xs: 'text',
    },
    fontWeight: {
      bold: 'number',
      extrabold: 'number',
      light: 'number',
      medium: 'number',
      normal: 'number',
      semibold: 'number',
    },
    letterSpacing: { normal: 'text', tight: 'text', wide: 'text' },
    lineHeight: {
      loose: 'number',
      normal: 'number',
      relaxed: 'number',
      tight: 'number',
    },
  },
} as const;
