import { vi } from 'vitest';
import type { CheckoutPaymentDispatchContext } from './checkout-payment-dispatch-context';

export function paymentDispatchContext(): CheckoutPaymentDispatchContext {
  return {
    merchant: { id: 'merchant-1', slug: 'shop' },
    order: { id: 'order-1', tracking_token: 'token-1', total: 1000 },
    paymentMethod: 'paystack',
    total: 1000,
    paymentAmount: 800,
    createdOrderNumber: 'ORD-1',
    orderChargeCurrency: 'NGN',
    currencyCode: 'NGN',
    firstName: 'Ada',
    lastName: 'Eze',
    customerEmail: 'ada@example.com',
    customerPhone: '+2348012345678',
    billingAddress: {
      line1: '1 Test St',
      city: 'Lagos',
      state: 'Lagos',
      country: 'NG',
    },
    checkoutFingerprint: 'fingerprint',
    checkoutCart: [{ name: 'Phone' }],
    cart: [{ name: 'Phone' }],
    orderItems: [],
    walletFundedTransfer: { start: vi.fn(async () => 'fallback' as const) },
    waitForResolvedStorefrontCustomerAuth: vi.fn(async () => true),
    setIsProcessing: vi.fn(),
    isOrderInFlightRef: { current: true },
    setDvaData: vi.fn(),
    setDvaCountdown: vi.fn(),
    setIsInitializingDva: vi.fn(),
    setRedvaultStatus: vi.fn(),
    setPendingCryptoOrder: vi.fn(),
    setShowCryptoSelector: vi.fn(),
    setCryptoPaymentData: vi.fn(),
    capturePaymentStarted: vi.fn(),
    hasPaymentStarted: vi.fn(() => false),
    setInitializedReference: vi.fn(),
    clearPendingCheckoutOrder: vi.fn(),
    clearCheckoutSession: vi.fn(),
    clearCart: vi.fn(),
    navigate: vi.fn(),
    redirect: vi.fn(),
    completeSignup: vi.fn(async () => undefined),
    payForMeDetails: { name: 'Payer' },
  };
}
