import type { StorefrontEdgeInventory } from './storefront-edge-inventory-types';
import { mediaSubresource } from './storefront-edge-media-subresource-support';

type InventoryRow = StorefrontEdgeInventory['rows'][number];

/** Footer, blog, chat, insurance, and post-purchase navigations. */
export const STOREFRONT_EDGE_MEDIA_SUBRESOURCE_NAVIGATION_ROWS: readonly InventoryRow[] =
  [
    mediaSubresource(
      'device-swap-whatsapp-navigation',
      'configured_whatsapp_origin',
      'apps/web/src/components/storefront/ogabassey/pages/swap.tsx'
    ),
    mediaSubresource(
      'footer-google-maps-navigation',
      'configured_google_maps_origin',
      'apps/web/src/components/storefront/ogabassey/components/Footer.tsx'
    ),
    mediaSubresource(
      'help-google-maps-navigation',
      'configured_google_maps_origin',
      'apps/web/src/components/storefront/ogabassey/pages/help-support.tsx'
    ),
    mediaSubresource(
      'blog-share-twitter-blog-post-body',
      'configured_twitter_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/blog-post-body.tsx'
    ),
    mediaSubresource(
      'blog-share-meta-blog-post-body',
      'configured_meta_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/blog-post-body.tsx'
    ),
    mediaSubresource(
      'blog-share-linkedin-blog-post-body',
      'configured_external_media_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/blog-post-body.tsx'
    ),
    mediaSubresource(
      'blog-share-twitter-blog-post-body-alt',
      'configured_twitter_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/BlogPostBody.tsx'
    ),
    mediaSubresource(
      'blog-share-meta-blog-post-body-alt',
      'configured_meta_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/BlogPostBody.tsx'
    ),
    mediaSubresource(
      'blog-share-linkedin-blog-post-body-alt',
      'configured_external_media_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/BlogPostBody.tsx'
    ),
    mediaSubresource(
      'blog-video-panel-youtube-thumbnail',
      'configured_external_media_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/BlogVideoPanel.tsx'
    ),
    mediaSubresource(
      'blog-video-panel-youtube-navigation',
      'configured_external_media_origin',
      'apps/web/src/app/(storefront)/[slug]/(blog)/blog/[postSlug]/BlogVideoPanel.tsx'
    ),
    mediaSubresource(
      'chat-markdown-image',
      'configured_external_media_origin',
      'apps/web/src/components/storefront/ogabassey/components/chat/markdown-renderer.tsx'
    ),
    mediaSubresource(
      'chat-markdown-link-navigation',
      'configured_external_media_origin',
      'apps/web/src/components/storefront/ogabassey/components/chat/markdown-renderer.tsx'
    ),
    mediaSubresource(
      'track-order-carrier-navigation',
      'configured_carrier_tracking_origin',
      'apps/web/src/app/(storefront)/[slug]/(commerce)/track-order/page.tsx'
    ),
    mediaSubresource(
      'mycover-flow-client-navigation',
      'configured_mycover_flow_origin',
      'apps/web/src/app/(storefront)/[slug]/(customer)/account/orders/[orderId]/insurance/insurance-policy-client.tsx'
    ),
    mediaSubresource(
      'mycover-flow-footer-navigation',
      'configured_mycover_flow_origin',
      'apps/web/src/app/(storefront)/[slug]/(customer)/account/orders/[orderId]/insurance/insurance-policy-footer-actions.tsx'
    ),
    mediaSubresource(
      'mycover-certificate-client-navigation',
      'configured_mycover_certificate_origin',
      'apps/web/src/app/(storefront)/[slug]/(customer)/account/orders/[orderId]/insurance/insurance-policy-client.tsx'
    ),
    mediaSubresource(
      'mycover-certificate-footer-navigation',
      'configured_mycover_certificate_origin',
      'apps/web/src/app/(storefront)/[slug]/(customer)/account/orders/[orderId]/insurance/insurance-policy-footer-actions.tsx'
    ),
    mediaSubresource(
      'post-purchase-google-review-checkout-success',
      'configured_google_maps_origin',
      'apps/web/src/app/(storefront)/[slug]/(commerce)/checkout/success/page.tsx'
    ),
    mediaSubresource(
      'post-purchase-google-review-commerce-order-success',
      'configured_google_maps_origin',
      'apps/web/src/app/(storefront)/[slug]/(commerce)/order-success/page.tsx'
    ),
    mediaSubresource(
      'post-purchase-google-review-customer-order',
      'configured_google_maps_origin',
      'apps/web/src/app/(storefront)/[slug]/(customer)/account/orders/[orderId]/customer-order-actions.tsx'
    ),
    mediaSubresource(
      'footer-merchant-social-navigation',
      'configured_merchant_social_origin',
      'apps/web/src/components/storefront/ogabassey/components/Footer.tsx'
    ),
    mediaSubresource(
      'footer-app-store-navigation',
      'configured_app_store_origin',
      'apps/web/src/components/storefront/ogabassey/components/FooterAppPayments.tsx'
    ),
    mediaSubresource(
      'footer-play-store-navigation',
      'configured_play_store_origin',
      'apps/web/src/components/storefront/ogabassey/components/FooterAppPayments.tsx'
    ),
    mediaSubresource(
      'receipt-claim-app-store-navigation',
      'configured_app_store_origin',
      'apps/web/src/components/storefront/ogabassey/pages/receipt-claim-app-download-banner.tsx'
    ),
    mediaSubresource(
      'receipt-claim-play-store-navigation',
      'configured_play_store_origin',
      'apps/web/src/components/storefront/ogabassey/pages/receipt-claim-app-download-banner.tsx'
    ),
  ];
