// DO NOT EDIT — generated by `node scripts/generate-ogabassey-hero-snapshots.mjs`.
// Same-origin AVIF snapshots for the OgaBassey mobile home-hero slide-0
// image, keyed by tenant slug then exact CDN source URL. A source URL with
// no entry here renders the legacy CDN path (rotation-safe by construction:
// rotated content misses its key and falls back instead of mismatching).
// Manifest version: 1. Generated: 2026-09-28T18:47:50.156Z.

export interface OgabasseyHomeHeroSnapshotManifestEntry {
  sourceUrl: string;
  srcSet: string;
  href: string;
  /** Encode quality the snapshot was baked at; must equal
   *  MOBILE_HERO_IMAGE_QUALITY (asserted by unit test). */
  quality: number;
  /** Width descriptors present in srcSet (ascending). */
  widths: number[];
  /** sha256 of the source bytes the snapshot was baked from (audit only;
   *  runtime matching is by exact sourceUrl key, never by hash). */
  sourceSha256: string;
}

export const OGABASSEY_HOME_HERO_SNAPSHOT_MANIFEST_VERSION = 1;

export const OGABASSEY_HOME_HERO_SNAPSHOT_MANIFEST: Record<
  string,
  Record<string, OgabasseyHomeHeroSnapshotManifestEntry>
> = {
  ogabassey: {
    'https://cdn.ogabassey.com/core-assets/products/premium-laptops/dell-alienware-m18-r2.jpg':
      {
        sourceUrl:
          'https://cdn.ogabassey.com/core-assets/products/premium-laptops/dell-alienware-m18-r2.jpg',
        srcSet:
          '/_hero/ogabassey/ad69426ce2b4-640.avif 640w, /_hero/ogabassey/ad69426ce2b4-750.avif 750w, /_hero/ogabassey/ad69426ce2b4-828.avif 828w, /_hero/ogabassey/ad69426ce2b4-1080.avif 1080w, /_hero/ogabassey/ad69426ce2b4-1200.avif 1200w',
        href: '/_hero/ogabassey/ad69426ce2b4-1080.avif',
        quality: 70,
        widths: [640, 750, 828, 1080, 1200],
        sourceSha256:
          'ad69426ce2b4b2135bc4bb0732fe19885af6c3fe34ae93ef7ba58c9febf0e26b',
      },
  },
};
