import { StyleSheet } from 'react-native';
import { RADIUS, SPACING } from '@/constants/theme';

export const NEW_ORDER_FOOTER_BASE_PADDING_BOTTOM = 20;

export const styles = StyleSheet.create({
  container: { flex: 1 },
  content: { gap: SPACING.md, padding: SPACING.md },
  card: {
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
  },
  listRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    padding: 16,
  },
  iconBox: {
    alignItems: 'center',
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  listLabel: { fontSize: 14, fontWeight: '500' },
  listValue: { fontSize: 14, marginLeft: 'auto' },
  listSubValue: { fontSize: 13, marginTop: 2 },
  section: { marginTop: 8 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    opacity: 0.7,
  },
  sectionEyebrow: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  channelScroll: { gap: 8, paddingRight: 16 },
  channelPill: {
    alignItems: 'center',
    borderRadius: 100,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  channelText: { fontSize: 13, fontWeight: '600' },
  customerSearchBody: {
    flex: 1,
    minHeight: 0,
  },
  customerList: {
    flex: 1,
    minHeight: 0,
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  actionBtn: {
    alignItems: 'center',
    borderRadius: RADIUS.md,
    borderStyle: 'dashed',
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    padding: 12,
  },
  actionBtnText: { fontSize: 14, fontWeight: '500' },
  emptyState: {
    alignItems: 'center',
    borderRadius: RADIUS.md,
    borderStyle: 'dashed',
    borderWidth: 1,
    justifyContent: 'center',
    padding: 32,
  },
  itemCard: {
    alignItems: 'center',
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 12,
  },
  itemThumbnail: {
    alignItems: 'center',
    borderRadius: 14,
    height: 54,
    justifyContent: 'center',
    width: 54,
  },
  qtyBadge: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  itemTitle: { fontSize: 15, fontWeight: '600' },
  itemActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  qtyBtn: {
    alignItems: 'center',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  summaryContainer: {
    borderTopWidth: 1,
    marginTop: 16,
    paddingTop: 8,
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  summaryLabel: { fontSize: 14, fontWeight: '500' },
  summaryValue: { fontSize: 14, fontWeight: '600' },
  notesInput: {
    borderRadius: RADIUS.md,
    height: 80,
    padding: 12,
    textAlignVertical: 'top',
  },
  footer: {
    elevation: 10,
    gap: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  paymentStatusField: {
    gap: 8,
  },
  footerFieldLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  paymentToggle: {
    borderRadius: RADIUS.lg,
    flexDirection: 'row',
    padding: 4,
  },
  toggleOption: {
    alignItems: 'center',
    borderRadius: RADIUS.md,
    flexDirection: 'row',
    flex: 1,
    gap: 6,
    justifyContent: 'center',
    paddingVertical: 8,
  },
  toggleText: { fontSize: 12, fontWeight: '700' },
  footerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  payBtn: {
    alignItems: 'center',
    borderRadius: 100,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 24,
    paddingVertical: 14,
  },
  payBtnText: { fontSize: 16, fontWeight: 'bold' },
  quickAddMatches: {
    gap: 8,
  },
  quickAddMatchRow: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  quickAddNameInput: {
    minHeight: 52,
  },
  quickAddAmountRow: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  quickAddAmountCurrency: {
    borderRightWidth: 1,
    fontSize: 13,
    fontWeight: '700',
    minWidth: 48,
    paddingRight: 12,
  },
  quickAddAmountInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  searchBox: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    margin: 16,
    padding: 12,
  },
  productItem: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  modalKeyboardCenterContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  dialog: {
    alignSelf: 'center',
    borderRadius: 20,
    gap: 16,
    padding: 24,
    width: '90%',
  },
  dialogTitle: { fontSize: 18, fontWeight: 'bold' },
  dialogInput: { borderRadius: 12, padding: 14 },
  dialogActions: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  dialogBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  sheetInput: {
    borderRadius: 12,
    fontSize: 16,
    marginBottom: 16,
    padding: 16,
  },
  label: { fontSize: 13, fontWeight: '600' },
  input: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
});
