import type { Layouts } from './analytics-grid-layouts';

export type AnalyticsGridLayouts = Layouts;

export const DEFAULT_LAYOUTS: AnalyticsGridLayouts = {
  lg: [
    // Row 1: Primary KPIs (3 cards across -> w: 4)
    { i: 'summary-revenue', x: 0, y: 0, w: 4, h: 1 },
    { i: 'summary-orders', x: 4, y: 0, w: 4, h: 1 },
    { i: 'summary-profit', x: 8, y: 0, w: 4, h: 1 },

    // Row 2: Primary KPIs continued
    { i: 'summary-customers', x: 0, y: 1, w: 4, h: 1 },
    { i: 'summary-tax', x: 4, y: 1, w: 4, h: 1 },
    { i: 'summary-active', x: 8, y: 1, w: 4, h: 1 },

    // Row 3: Secondary KPIs (4 cards across -> w: 3)
    { i: 'summary-aov', x: 0, y: 2, w: 3, h: 1 },
    { i: 'summary-margin', x: 3, y: 2, w: 3, h: 1 },
    { i: 'summary-refund-rate', x: 6, y: 2, w: 3, h: 1 },
    { i: 'summary-revenue-per-customer', x: 9, y: 2, w: 3, h: 1 },

    // Row 4: Payment Methods (fits in 4 cols flow?)
    // Payment methods was w:4 h:2. Let's keep it similar or adapt.
    // In CSS grid secondary, payment methods was explicitly NOT in the secondary grid (lines 649-686).
    // It was in "Charts & Detailed Views Grid" (line 689) which is lg:grid-cols-3.
    // So Payment Methods is in a 3-col grid. w: 4 is correct for 12-col grid.

    // Row 4: Charts & Detailed Views (3 cols -> w: 4)
    { i: 'revenue-chart', x: 0, y: 3, w: 8, h: 3 }, // Spans 2 cols (2/3) -> w: 8
    { i: 'payment-methods', x: 8, y: 3, w: 4, h: 3 }, // Spans 1 col (1/3) -> w: 4

    // Row 5: Lists (stacked)
    { i: 'sales-channel', x: 0, y: 6, w: 6, h: 3 },
    { i: 'recent-sales', x: 6, y: 6, w: 6, h: 3 },
    { i: 'top-products', x: 0, y: 9, w: 12, h: 3 },
    { i: 'summary-units', x: 0, y: 12, w: 3, h: 1 },
    { i: 'analytics-highlights', x: 0, y: 13, w: 12, h: 2 },
    { i: 'financial-summary', x: 0, y: 15, w: 12, h: 2 },
    { i: 'orders-chart', x: 0, y: 17, w: 8, h: 3 },
    { i: 'brand-breakdown', x: 8, y: 17, w: 4, h: 3 },
    { i: 'customer-breakdown', x: 0, y: 20, w: 6, h: 3 },
    { i: 'supplier-breakdown', x: 6, y: 20, w: 6, h: 3 },
    { i: 'blog-performance', x: 0, y: 23, w: 12, h: 2 },

    // Inventory widgets
    { i: 'inventory-summary', x: 0, y: 0, w: 3, h: 1 },
    { i: 'inventory-alerts', x: 3, y: 0, w: 4, h: 2 },
    { i: 'inventory-forecast', x: 7, y: 0, w: 5, h: 3 },
    { i: 'low-stock-products', x: 0, y: 1, w: 3, h: 2 },

    // Segment widgets
    { i: 'segment-overview', x: 0, y: 0, w: 3, h: 2 },
    { i: 'segment-distribution', x: 3, y: 0, w: 3, h: 2 },
    { i: 'at-risk-customers', x: 6, y: 0, w: 3, h: 2 },
    { i: 'champions-list', x: 9, y: 0, w: 3, h: 2 },

    // Ad analytics widgets
    { i: 'ads-overview', x: 0, y: 0, w: 6, h: 2 },
    { i: 'ads-platforms', x: 6, y: 0, w: 6, h: 2 },
    { i: 'ads-attribution', x: 0, y: 2, w: 6, h: 2 },
    { i: 'ads-privacy', x: 6, y: 2, w: 6, h: 2 },
    { i: 'ads-reporting', x: 0, y: 4, w: 12, h: 3 },
    { i: 'social-ads-reporting', x: 0, y: 7, w: 12, h: 5 },
  ],
  md: [
    // On md (10 cols), make cards take full width or half width
    { i: 'sales-channel', x: 5, y: 0, w: 5, h: 3 },
    { i: 'summary-revenue', x: 0, y: 0, w: 5, h: 1 },
    { i: 'summary-orders', x: 5, y: 1, w: 5, h: 1 },
    { i: 'summary-profit', x: 5, y: 1, w: 5, h: 1 },
    { i: 'summary-customers', x: 0, y: 1, w: 5, h: 1 },
    { i: 'summary-tax', x: 0, y: 1, w: 5, h: 1 },
    { i: 'summary-active', x: 0, y: 2, w: 5, h: 1 },
    { i: 'summary-aov', x: 0, y: 2, w: 5, h: 1 },
    { i: 'summary-margin', x: 5, y: 2, w: 5, h: 1 },
    { i: 'summary-refund-rate', x: 5, y: 2, w: 5, h: 1 },
    { i: 'summary-revenue-per-customer', x: 0, y: 3, w: 5, h: 1 },
    { i: 'revenue-chart', x: 0, y: 4, w: 10, h: 3 },
    { i: 'payment-methods', x: 0, y: 7, w: 5, h: 3 },
    { i: 'recent-sales', x: 0, y: 10, w: 5, h: 3 },
    { i: 'top-products', x: 5, y: 10, w: 5, h: 3 },
    { i: 'summary-units', x: 0, y: 13, w: 5, h: 1 },
    { i: 'analytics-highlights', x: 0, y: 14, w: 10, h: 2 },
    { i: 'financial-summary', x: 0, y: 16, w: 10, h: 2 },
    { i: 'orders-chart', x: 0, y: 18, w: 10, h: 3 },
    { i: 'brand-breakdown', x: 0, y: 21, w: 5, h: 3 },
    { i: 'customer-breakdown', x: 5, y: 21, w: 5, h: 3 },
    { i: 'supplier-breakdown', x: 0, y: 24, w: 10, h: 3 },
    { i: 'blog-performance', x: 0, y: 27, w: 10, h: 2 },
    { i: 'inventory-alerts', x: 0, y: 0, w: 5, h: 2 },
    { i: 'inventory-forecast', x: 5, y: 0, w: 5, h: 3 },
    { i: 'inventory-summary', x: 0, y: 2, w: 5, h: 1 },
    { i: 'low-stock-products', x: 5, y: 3, w: 5, h: 2 },
    { i: 'segment-overview', x: 0, y: 0, w: 5, h: 2 },
    { i: 'segment-distribution', x: 5, y: 0, w: 5, h: 2 },
    { i: 'at-risk-customers', x: 0, y: 2, w: 5, h: 2 },
    { i: 'champions-list', x: 5, y: 2, w: 5, h: 2 },
    { i: 'ads-overview', x: 0, y: 0, w: 5, h: 2 },
    { i: 'ads-platforms', x: 5, y: 0, w: 5, h: 2 },
    { i: 'ads-attribution', x: 0, y: 2, w: 5, h: 2 },
    { i: 'ads-privacy', x: 5, y: 2, w: 5, h: 2 },
    { i: 'ads-reporting', x: 0, y: 4, w: 10, h: 3 },
    { i: 'social-ads-reporting', x: 0, y: 7, w: 10, h: 5 },
  ],
  sm: [
    // On sm (6 cols), stack in 2 columns
    { i: 'sales-channel', x: 0, y: 10, w: 6, h: 3 },
    { i: 'summary-revenue', x: 0, y: 0, w: 3, h: 1 },
    { i: 'summary-orders', x: 3, y: 0, w: 3, h: 1 },
    { i: 'summary-profit', x: 3, y: 0, w: 3, h: 1 },
    { i: 'summary-customers', x: 0, y: 1, w: 3, h: 1 },
    { i: 'summary-tax', x: 0, y: 1, w: 3, h: 1 },
    { i: 'summary-active', x: 3, y: 1, w: 3, h: 1 },
    { i: 'summary-aov', x: 3, y: 1, w: 3, h: 1 },
    { i: 'summary-margin', x: 0, y: 2, w: 3, h: 1 },
    { i: 'summary-refund-rate', x: 0, y: 2, w: 3, h: 1 },
    { i: 'summary-revenue-per-customer', x: 3, y: 2, w: 3, h: 1 },
    { i: 'revenue-chart', x: 0, y: 3, w: 6, h: 3 },
    { i: 'payment-methods', x: 0, y: 6, w: 6, h: 3 },
    { i: 'recent-sales', x: 0, y: 13, w: 6, h: 3 },
    { i: 'top-products', x: 0, y: 16, w: 6, h: 3 },
    { i: 'summary-units', x: 0, y: 19, w: 6, h: 1 },
    { i: 'analytics-highlights', x: 0, y: 20, w: 6, h: 2 },
    { i: 'financial-summary', x: 0, y: 22, w: 6, h: 2 },
    { i: 'orders-chart', x: 0, y: 24, w: 6, h: 3 },
    { i: 'brand-breakdown', x: 0, y: 27, w: 6, h: 3 },
    { i: 'customer-breakdown', x: 0, y: 30, w: 6, h: 3 },
    { i: 'supplier-breakdown', x: 0, y: 33, w: 6, h: 3 },
    { i: 'blog-performance', x: 0, y: 36, w: 6, h: 2 },
    { i: 'inventory-alerts', x: 0, y: 0, w: 3, h: 2 },
    { i: 'inventory-forecast', x: 3, y: 0, w: 3, h: 3 },
    { i: 'inventory-summary', x: 0, y: 2, w: 3, h: 1 },
    { i: 'low-stock-products', x: 0, y: 3, w: 6, h: 2 },
    { i: 'segment-overview', x: 0, y: 0, w: 3, h: 2 },
    { i: 'segment-distribution', x: 3, y: 0, w: 3, h: 2 },
    { i: 'at-risk-customers', x: 0, y: 2, w: 6, h: 2 },
    { i: 'champions-list', x: 0, y: 4, w: 6, h: 2 },
    { i: 'ads-overview', x: 0, y: 0, w: 6, h: 2 },
    { i: 'ads-platforms', x: 0, y: 2, w: 6, h: 2 },
    { i: 'ads-attribution', x: 0, y: 4, w: 6, h: 2 },
    { i: 'ads-privacy', x: 0, y: 6, w: 6, h: 2 },
    { i: 'ads-reporting', x: 0, y: 8, w: 6, h: 3 },
    { i: 'social-ads-reporting', x: 0, y: 11, w: 6, h: 6 },
  ],
  xs: [
    // On xs (4 cols), cards take 2 or 4 cols
    { i: 'sales-channel', x: 0, y: 10, w: 4, h: 3 },
    { i: 'summary-revenue', x: 0, y: 0, w: 2, h: 1 },
    { i: 'summary-orders', x: 2, y: 0, w: 2, h: 1 },
    { i: 'summary-profit', x: 2, y: 0, w: 2, h: 1 },
    { i: 'summary-customers', x: 0, y: 1, w: 2, h: 1 },
    { i: 'summary-tax', x: 0, y: 1, w: 2, h: 1 },
    { i: 'summary-active', x: 2, y: 1, w: 2, h: 1 },
    { i: 'summary-aov', x: 2, y: 1, w: 2, h: 1 },
    { i: 'summary-margin', x: 0, y: 2, w: 2, h: 1 },
    { i: 'summary-refund-rate', x: 0, y: 2, w: 2, h: 1 },
    { i: 'summary-revenue-per-customer', x: 2, y: 2, w: 2, h: 1 },
    { i: 'revenue-chart', x: 0, y: 3, w: 4, h: 3 },
    { i: 'payment-methods', x: 0, y: 6, w: 4, h: 3 },
    { i: 'recent-sales', x: 0, y: 13, w: 4, h: 3 },
    { i: 'top-products', x: 0, y: 16, w: 4, h: 3 },
    { i: 'summary-units', x: 0, y: 19, w: 4, h: 1 },
    { i: 'analytics-highlights', x: 0, y: 20, w: 4, h: 2 },
    { i: 'financial-summary', x: 0, y: 22, w: 4, h: 2 },
    { i: 'orders-chart', x: 0, y: 24, w: 4, h: 3 },
    { i: 'brand-breakdown', x: 0, y: 27, w: 4, h: 3 },
    { i: 'customer-breakdown', x: 0, y: 30, w: 4, h: 3 },
    { i: 'supplier-breakdown', x: 0, y: 33, w: 4, h: 3 },
    { i: 'blog-performance', x: 0, y: 36, w: 4, h: 2 },
    { i: 'inventory-alerts', x: 0, y: 0, w: 2, h: 2 },
    { i: 'inventory-forecast', x: 2, y: 0, w: 2, h: 3 },
    { i: 'inventory-summary', x: 0, y: 2, w: 2, h: 1 },
    { i: 'low-stock-products', x: 0, y: 3, w: 4, h: 2 },
    { i: 'segment-overview', x: 0, y: 0, w: 2, h: 2 },
    { i: 'segment-distribution', x: 2, y: 0, w: 2, h: 2 },
    { i: 'at-risk-customers', x: 0, y: 2, w: 4, h: 2 },
    { i: 'champions-list', x: 0, y: 4, w: 4, h: 2 },
    { i: 'ads-overview', x: 0, y: 0, w: 4, h: 2 },
    { i: 'ads-platforms', x: 0, y: 2, w: 4, h: 2 },
    { i: 'ads-attribution', x: 0, y: 4, w: 4, h: 2 },
    { i: 'ads-privacy', x: 0, y: 6, w: 4, h: 2 },
    { i: 'ads-reporting', x: 0, y: 8, w: 4, h: 3 },
    { i: 'social-ads-reporting', x: 0, y: 11, w: 4, h: 7 },
  ],
  xxs: [
    // On xxs (2 cols), everything full width
    { i: 'sales-channel', x: 0, y: 10, w: 2, h: 3 },
    { i: 'summary-revenue', x: 0, y: 0, w: 2, h: 1 },
    { i: 'summary-orders', x: 0, y: 1, w: 2, h: 1 },
    { i: 'summary-profit', x: 0, y: 1, w: 2, h: 1 },
    { i: 'summary-customers', x: 0, y: 2, w: 2, h: 1 },
    { i: 'summary-tax', x: 0, y: 2, w: 2, h: 1 },
    { i: 'summary-active', x: 0, y: 3, w: 2, h: 1 },
    { i: 'summary-aov', x: 0, y: 3, w: 2, h: 1 },
    { i: 'summary-margin', x: 0, y: 4, w: 2, h: 1 },
    { i: 'summary-refund-rate', x: 0, y: 4, w: 2, h: 1 },
    { i: 'summary-revenue-per-customer', x: 0, y: 5, w: 2, h: 1 },
    { i: 'revenue-chart', x: 0, y: 6, w: 2, h: 3 },
    { i: 'payment-methods', x: 0, y: 9, w: 2, h: 3 },
    { i: 'recent-sales', x: 0, y: 13, w: 2, h: 3 },
    { i: 'top-products', x: 0, y: 16, w: 2, h: 3 },
    { i: 'summary-units', x: 0, y: 19, w: 2, h: 1 },
    { i: 'analytics-highlights', x: 0, y: 20, w: 2, h: 2 },
    { i: 'financial-summary', x: 0, y: 22, w: 2, h: 2 },
    { i: 'orders-chart', x: 0, y: 24, w: 2, h: 3 },
    { i: 'brand-breakdown', x: 0, y: 27, w: 2, h: 3 },
    { i: 'customer-breakdown', x: 0, y: 30, w: 2, h: 3 },
    { i: 'supplier-breakdown', x: 0, y: 33, w: 2, h: 3 },
    { i: 'blog-performance', x: 0, y: 36, w: 2, h: 2 },
    { i: 'inventory-alerts', x: 0, y: 0, w: 2, h: 2 },
    { i: 'inventory-forecast', x: 0, y: 2, w: 2, h: 3 },
    { i: 'inventory-summary', x: 0, y: 5, w: 2, h: 1 },
    { i: 'low-stock-products', x: 0, y: 6, w: 2, h: 2 },
    { i: 'segment-overview', x: 0, y: 0, w: 2, h: 2 },
    { i: 'segment-distribution', x: 0, y: 2, w: 2, h: 2 },
    { i: 'at-risk-customers', x: 0, y: 4, w: 2, h: 2 },
    { i: 'champions-list', x: 0, y: 6, w: 2, h: 2 },
    { i: 'ads-overview', x: 0, y: 0, w: 2, h: 2 },
    { i: 'ads-platforms', x: 0, y: 2, w: 2, h: 2 },
    { i: 'ads-attribution', x: 0, y: 4, w: 2, h: 2 },
    { i: 'ads-privacy', x: 0, y: 6, w: 2, h: 2 },
    { i: 'ads-reporting', x: 0, y: 8, w: 2, h: 3 },
    { i: 'social-ads-reporting', x: 0, y: 11, w: 2, h: 8 },
  ],
};
