import { StyleSheet } from 'react-native';
import { RADIUS, SPACING, TYPOGRAPHY } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  headerButton: { padding: SPACING.sm },
  summaryContainer: { padding: SPACING.lg, paddingBottom: SPACING.sm },
  summaryCard: {
    padding: SPACING.xl,
    borderRadius: RADIUS.xl,
  },
  summaryLabel: {
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    marginBottom: SPACING.xs,
  },
  summaryAmount: {
    fontSize: TYPOGRAPHY.size['3xl'],
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    marginBottom: SPACING.md,
  },
  summaryTrend: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  summaryTrendText: {
    fontSize: TYPOGRAPHY.size.xs,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
  },
  filterButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: RADIUS.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: SPACING.xs,
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.sm,
    minHeight: SPACING.touchTarget,
    paddingHorizontal: SPACING.md,
  },
  filterButtonText: {
    fontFamily: TYPOGRAPHY.fontFamily.semiBold,
    fontSize: TYPOGRAPHY.size.sm,
  },
  filterBadge: {
    borderRadius: RADIUS.full,
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontSize: TYPOGRAPHY.size.xs,
    minWidth: 20,
    overflow: 'hidden',
    paddingHorizontal: SPACING.xs,
    textAlign: 'center',
  },
  filterSheetHeader: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: SPACING.md,
    paddingBottom: SPACING.md,
  },
  filterSheetTitle: {
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontSize: TYPOGRAPHY.size.lg,
  },
  filterSheetLabel: {
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    fontSize: TYPOGRAPHY.size.sm,
    marginBottom: SPACING.xs,
    marginTop: SPACING.md,
  },
  filterChoiceList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.xs,
  },
  filterSheetOption: {
    alignItems: 'center',
    borderRadius: RADIUS.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: SPACING.xs,
    minHeight: SPACING.touchTarget,
    paddingHorizontal: SPACING.md,
    justifyContent: 'center',
  },
  filterSheetInlineOption: {
    minHeight: SPACING.touchTarget,
    paddingHorizontal: SPACING.sm,
    justifyContent: 'center',
  },
  filterDateRange: {
    flexDirection: 'row',
    gap: SPACING.sm,
    marginTop: SPACING.sm,
  },
  filterDateButton: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    flex: 1,
    minHeight: SPACING.touchTarget,
    justifyContent: 'center',
    paddingHorizontal: SPACING.md,
  },
  lockedBranchText: {
    fontSize: TYPOGRAPHY.size.sm,
    minHeight: SPACING.touchTarget,
    paddingVertical: SPACING.sm,
  },
  filterActions: {
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: SPACING.sm,
    marginTop: SPACING.lg,
    paddingTop: SPACING.md,
  },
  filterResetButton: {
    alignItems: 'center',
    borderRadius: RADIUS.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: SPACING.touchTarget,
  },
  filterApplyButton: {
    alignItems: 'center',
    borderRadius: RADIUS.md,
    flex: 1,
    justifyContent: 'center',
    minHeight: SPACING.touchTarget,
  },
  listContent: { padding: SPACING.lg, paddingBottom: 100 },
  expenseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: SPACING.md,
    marginBottom: SPACING.md,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
  },
  expenseMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    minHeight: SPACING.touchTarget,
  },
  categoryIcon: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.md,
  },
  expenseDetails: { flex: 1 },
  expenseCategory: {
    fontSize: TYPOGRAPHY.size.md,
    fontFamily: TYPOGRAPHY.fontFamily.semiBold,
    marginBottom: 2,
  },
  expenseDescription: {
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    marginBottom: 2,
  },
  expenseDate: {
    fontSize: TYPOGRAPHY.size.xs,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
  },
  expenseAmount: { alignItems: 'flex-end' },
  receiptIcon: { marginTop: SPACING.xs },
  amountText: {
    fontSize: TYPOGRAPHY.size.md,
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  editButton: {
    alignItems: 'center',
    borderRadius: RADIUS.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: SPACING.xs,
    justifyContent: 'center',
    marginLeft: SPACING.sm,
    minHeight: SPACING.touchTarget,
    paddingHorizontal: SPACING.sm,
  },
  editButtonText: {
    fontFamily: TYPOGRAPHY.fontFamily.semiBold,
    fontSize: TYPOGRAPHY.size.sm,
  },
  fab: {
    position: 'absolute',
    bottom: SPACING.xl,
    right: SPACING.xl,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING['3xl'],
    marginTop: SPACING.xl,
  },
  emptyText: {
    marginTop: SPACING.md,
    fontSize: TYPOGRAPHY.size.md,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    textAlign: 'center',
  },
  emptySubtext: {
    marginTop: SPACING.xs,
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    textAlign: 'center',
  },
  emptyButton: {
    marginTop: SPACING.lg,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.full,
    borderWidth: 1,
  },
  emptyButtonText: {
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: TYPOGRAPHY.fontFamily.semiBold,
  },
  sectionHeader: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    justifyContent: 'center',
  },
  groupSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.xs,
  },
  groupSectionHeaderLabel: {
    fontSize: TYPOGRAPHY.size.md,
    fontFamily: TYPOGRAPHY.fontFamily.semiBold,
    flex: 1,
    flexShrink: 1,
    marginRight: SPACING.sm,
  },
  sectionHeaderLabel: {
    fontSize: TYPOGRAPHY.size.xs,
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sectionHeaderSummary: {
    flexDirection: 'row',
    flexShrink: 0,
    gap: SPACING.xs,
  },
  sectionHeaderTotal: {
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontSize: TYPOGRAPHY.size.xs,
  },
  sectionHeaderCount: {
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    fontSize: TYPOGRAPHY.size.xs,
  },
});
