import { fileURLToPath } from 'node:url';

const required = (name) => `\${${name}:?Secure setup required: ${name}}`;
const password = required('ISOLATED_POSTGRES_PASSWORD');
const authPassword = required('ISOLATED_AUTH_DB_PASSWORD');
const restPassword = required('ISOLATED_REST_DB_PASSWORD');
const jwt = required('ISOLATED_JWT_SECRET');
const apiOrigin = required('ISOLATED_API_ORIGIN');
const issuer = required('ISOLATED_AUTH_ISSUER');
const siteUrl = required('ISOLATED_SITE_URL');
const healthyDb = { db: { condition: 'service_healthy' } };

function service(image, memory, cpus, networks) {
  return {
    image,
    restart: 'no',
    mem_limit: memory,
    memswap_limit: memory,
    cpus,
    pids_limit: 128,
    networks,
    dns: ['127.0.0.1'],
    security_opt: ['no-new-privileges:true'],
    logging: { driver: 'none' },
  };
}

export function composeTemplate() {
  return {
    name: 'baci-isolated-savings',
    services: {
      db: {
        ...service('supabase/postgres:17.6.1.136', '2g', 1.5, ['database']),
        shm_size: '256m',
        environment: {
          POSTGRES_HOST: '/var/run/postgresql',
          PGPORT: '5432',
          POSTGRES_PORT: '5432',
          POSTGRES_DB: 'postgres',
          PGDATABASE: 'postgres',
          POSTGRES_PASSWORD: password,
          ISOLATED_AUTH_DB_PASSWORD: authPassword,
          ISOLATED_REST_DB_PASSWORD: restPassword,
          PGPASSWORD: password,
          JWT_SECRET: jwt,
          JWT_EXP: '900',
        },
        volumes: [
          'db-data:/var/lib/postgresql/data',
          'db-config:/etc/postgresql-custom',
          {
            type: 'bind',
            source: fileURLToPath(new URL('./bootstrap.sql', import.meta.url)),
            target: '/docker-entrypoint-initdb.d/init-scripts/99-isolated.sql',
            read_only: true,
            bind: { create_host_path: false },
          },
        ],
        command: [
          'postgres',
          '-c',
          'config_file=/etc/postgresql/postgresql.conf',
          '-c',
          'max_connections=60',
          '-c',
          'shared_buffers=256MB',
          '-c',
          'work_mem=4MB',
          '-c',
          'max_wal_size=1GB',
          '-c',
          'cron.launch_active_jobs=off',
          '-c',
          'pg_net.database_name=baci_disabled_background',
          '-c',
          'pg_stat_statements.track=none',
          '-c',
          'pg_stat_statements.track_utility=off',
          '-c',
          'log_statement=none',
          '-c',
          'log_min_messages=panic',
          '-c',
          'log_min_error_statement=panic',
          '-c',
          'log_error_verbosity=terse',
          '-c',
          'log_min_duration_statement=-1',
          '-c',
          'log_min_duration_sample=-1',
          '-c',
          'log_transaction_sample_rate=0',
          '-c',
          'log_duration=off',
          '-c',
          'log_connections=off',
          '-c',
          'log_disconnections=off',
          '-c',
          'log_parameter_max_length=0',
          '-c',
          'log_parameter_max_length_on_error=0',
          '-c',
          'logging_collector=off',
        ],
        healthcheck: {
          test: ['CMD', 'pg_isready', '-U', 'postgres', '-h', 'localhost'],
          interval: '5s',
          timeout: '5s',
          retries: 20,
          start_period: '60s',
        },
      },
      auth: {
        ...service('supabase/gotrue:v2.196.0', '512m', 0.5, [
          'database',
          'mail',
        ]),
        cap_drop: ['ALL'],
        depends_on: { ...healthyDb, mail: { condition: 'service_started' } },
        ports: ['127.0.0.1:15439:9999'],
        environment: {
          GOTRUE_API_HOST: '0.0.0.0',
          GOTRUE_API_PORT: '9999',
          API_EXTERNAL_URL: `${apiOrigin}/auth/v1`,
          GOTRUE_JWT_ISSUER: issuer,
          GOTRUE_DB_DRIVER: 'postgres',
          GOTRUE_DB_DATABASE_URL: `postgres://supabase_auth_admin:${authPassword}@db:5432/postgres`,
          GOTRUE_SITE_URL: siteUrl,
          GOTRUE_URI_ALLOW_LIST: siteUrl,
          GOTRUE_DISABLE_SIGNUP: 'true',
          GOTRUE_JWT_SECRET: jwt,
          GOTRUE_JWT_EXP: '900',
          GOTRUE_JWT_ADMIN_ROLES: 'service_role',
          GOTRUE_JWT_AUD: 'authenticated',
          GOTRUE_JWT_DEFAULT_GROUP_NAME: 'authenticated',
          GOTRUE_EXTERNAL_EMAIL_ENABLED: 'true',
          GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: 'false',
          GOTRUE_EXTERNAL_PHONE_ENABLED: 'false',
          GOTRUE_SMS_AUTOCONFIRM: 'false',
          GOTRUE_MAILER_AUTOCONFIRM: 'false',
          GOTRUE_SMTP_HOST: 'mail',
          GOTRUE_SMTP_PORT: '1025',
          GOTRUE_SMTP_ADMIN_EMAIL: 'auth@isolated.invalid',
          GOTRUE_SMTP_SENDER_NAME: 'Isolated savings test',
          GOTRUE_MAILER_URLPATHS_INVITE: '/auth/v1/verify',
          GOTRUE_MAILER_URLPATHS_CONFIRMATION: '/auth/v1/verify',
          GOTRUE_MAILER_URLPATHS_RECOVERY: '/auth/v1/verify',
          GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: '/auth/v1/verify',
        },
        healthcheck: {
          test: [
            'CMD',
            'wget',
            '--no-verbose',
            '--tries=1',
            '--spider',
            'http://localhost:9999/health',
          ],
          interval: '5s',
          timeout: '5s',
          retries: 20,
        },
      },
      rest: {
        ...service('postgrest/postgrest:v14.17', '256m', 0.5, ['database']),
        cap_drop: ['ALL'],
        depends_on: healthyDb,
        ports: ['127.0.0.1:15430:3000'],
        environment: {
          PGRST_DB_URI: `postgres://authenticator:${restPassword}@db:5432/postgres`,
          PGRST_DB_SCHEMAS: 'public',
          PGRST_DB_EXTRA_SEARCH_PATH: 'public',
          PGRST_DB_ANON_ROLE: 'anon',
          PGRST_JWT_SECRET: jwt,
          PGRST_DB_MAX_ROWS: '100',
          PGRST_DB_POOL: '10',
          PGRST_ADMIN_SERVER_HOST: 'localhost',
          PGRST_ADMIN_SERVER_PORT: '3001',
        },
        healthcheck: {
          test: ['CMD', 'postgrest', '--ready'],
          interval: '5s',
          timeout: '5s',
          retries: 20,
        },
      },
      mail: {
        ...service('axllent/mailpit:v1.31.1', '128m', 0.25, ['mail']),
        cap_drop: ['ALL'],
        environment: { MP_MAX_MESSAGES: '100', MP_SMTP_MAX_MESSAGE_SIZE: '1' },
        healthcheck: {
          test: ['CMD', '/mailpit', 'readyz'],
          interval: '5s',
          timeout: '5s',
          retries: 20,
        },
        tmpfs: ['/tmp:size=64m,mode=1777'],
      },
    },
    networks: {
      database: {
        internal: true,
        enable_ipv6: false,
        driver_opts: { 'com.docker.network.bridge.name': 'baci-stg-db' },
      },
      mail: {
        internal: true,
        enable_ipv6: false,
        driver_opts: { 'com.docker.network.bridge.name': 'baci-stg-mail' },
      },
    },
    volumes: { 'db-data': {}, 'db-config': {} },
  };
}
