export const acceptanceContract = Object.freeze({
  deadline: '2026-10-06T15:59:10Z',
  oldPrincipalKobo: 10000,
  globalCompanySandboxBudgetKobo: 10000,
  emptyGoalId: '9f01153c-1589-4dde-b9aa-8f644a846832',
  interestEnabledProviderWalletId: '01M3W0Y93XHJY9RPQ2G75X81WG',
  categories: {
    implemented: 'source-manifest',
    tested: 'synthetic-result',
    liveAuth: 'historical-note',
    financial: 'historical-note',
    genuineProvider: 'historical-note',
    device: 'historical-note',
  },
  parentContext: {
    provenance: 'user-supplied-2026-10-02-not-independently-refreshed',
    financialR8: 'reported-active',
    publicGateR2: 'reported-failed-being-fixed-separately',
    readOnlyRecovery: 'reported-independently-verified-no-financial-change',
    emptyGoal: 'reported-empty-interest-enabled-no-payout-namespace-policy',
    providerRates: 'confirmed-global-customer9-business3-dashboard-only',
    perWalletSplit: 'unavailable',
    genuineSandboxMonthlyPayout: 'cannot-be-tested-in-provider-sandbox',
  },
  pending: [
    'Parent pins independent current authenticated wallet/inbox readbacks.',
    'Parent pins r8 active runtime/deadline and complete protected-state proofs; public r2 remains a separate failed gate.',
    'Preserve old principal10000 and the global company budget10000; a new goal does not authorize a second budget.',
    'Independently prove current exact empty-goal/wallet binding, eligibility, opt-in and payout namespace/source/destination policy.',
    'Preserve provider-confirmed global customer9/business3 dashboard terms; do not infer a per-wallet split or apply a second split to customer net.',
    'Actual provider acceptance awaits genuine authenticated payout, durable receipt and independent credit/allocation reconciliation; sandbox cannot supply a genuine monthly payout.',
    'Approve separate native staging pins, signing/APNs/FCM and EAS identity/artifact; connect the phone and verify permission/token plus foreground/background/cold-start receipts and scoped refresh.',
    'Parent owns focused reporter tests, fresh global audit and remaining checkout/payment acceptance.',
  ],
});
