import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  toolbar: { paddingHorizontal: 16, paddingTop: 4 },
  quick: { flexDirection: 'row', minWidth: '100%', gap: 8, paddingVertical: 8 },
  quickPill: {
    minHeight: 40,
    paddingHorizontal: 10,
    minWidth: 96,
    justifyContent: 'center',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionHeader: {
    flexDirection: 'row',
    borderRadius: 12,
    padding: 2,
  },
  headerAction: {
    flex: 1,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 8,
  },
  headerDetail: { fontSize: 13, fontWeight: '500', flexShrink: 1 },
  sortLabel: { paddingVertical: 8 },
  choice: {
    minHeight: 48,
    minWidth: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderRadius: 16,
    justifyContent: 'center',
    marginBottom: 4,
  },
  chips: { paddingHorizontal: 16, gap: 8, paddingBottom: 6 },
  floating: {
    position: 'absolute',
    zIndex: 20,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 32,
    padding: 6,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  keyboard: { flex: 1, justifyContent: 'flex-end' },
  panel: { width: '100%', borderTopLeftRadius: 20, borderTopRightRadius: 20 },
  panelHeader: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heading: { fontSize: 18, fontWeight: '600', marginBottom: 10 },
  body: { flexShrink: 1 },
  section: { padding: 16, gap: 8 },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
  footer: { paddingHorizontal: 16, paddingTop: 8 },
});
