-- Keep Gemini Embedding 2 vectors separate from legacy content_embedding values.
-- The latter were generated by a retired model and cannot be compared safely.
CREATE TABLE public.product_discovery_embeddings (
  product_id uuid PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
  merchant_id uuid NOT NULL REFERENCES public.merchants(id) ON DELETE CASCADE,
  embedding extensions.vector(768) NOT NULL,
  source_updated_at timestamptz NOT NULL,
  model text NOT NULL DEFAULT 'gemini-embedding-2'
    CHECK (model = 'gemini-embedding-2'),
  generated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX product_discovery_embeddings_merchant_idx
  ON public.product_discovery_embeddings (merchant_id);
-- Exact cosine ordering after merchant filtering preserves small-merchant
-- recall. Add an approximate per-merchant index only after measuring scale.

ALTER TABLE public.product_discovery_embeddings ENABLE ROW LEVEL SECURITY;

CREATE POLICY product_discovery_embeddings_merchant_read
  ON public.product_discovery_embeddings FOR SELECT TO authenticated
  USING (public.has_merchant_access(merchant_id) AND EXISTS (
    SELECT 1 FROM public.products p
    WHERE p.id = product_discovery_embeddings.product_id
      AND p.merchant_id = product_discovery_embeddings.merchant_id
      AND p.status = 'active'
  ));

CREATE POLICY product_discovery_embeddings_merchant_insert
  ON public.product_discovery_embeddings FOR INSERT TO authenticated
  WITH CHECK (public.check_staff_permission((SELECT auth.uid()), merchant_id, 'products', 'edit') AND EXISTS (
    SELECT 1 FROM public.products p
    WHERE p.id = product_discovery_embeddings.product_id
      AND p.merchant_id = product_discovery_embeddings.merchant_id
  ));

CREATE POLICY product_discovery_embeddings_merchant_update
  ON public.product_discovery_embeddings FOR UPDATE TO authenticated
  USING (public.check_staff_permission((SELECT auth.uid()), merchant_id, 'products', 'edit'))
  WITH CHECK (public.check_staff_permission((SELECT auth.uid()), merchant_id, 'products', 'edit') AND EXISTS (
    SELECT 1 FROM public.products p
    WHERE p.id = product_discovery_embeddings.product_id
      AND p.merchant_id = product_discovery_embeddings.merchant_id
  ));

REVOKE ALL ON public.product_discovery_embeddings FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.product_discovery_embeddings TO authenticated;
GRANT INSERT, UPDATE ON public.product_discovery_embeddings TO authenticated;

-- Public callers receive only IDs and scores of active merchant products;
-- raw vectors remain readable only to the owning merchant under RLS.
CREATE FUNCTION public.search_product_discovery_embeddings(
  query_embedding extensions.vector(768),
  merchant_id_param uuid,
  result_limit integer DEFAULT 20
)
RETURNS TABLE (product_id uuid, similarity real)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT e.product_id, (1 - (e.embedding OPERATOR(extensions.<=>) query_embedding))::real
  FROM public.product_discovery_embeddings e
  JOIN public.products p ON p.id = e.product_id
  WHERE e.merchant_id = merchant_id_param
    AND p.merchant_id = merchant_id_param
    AND p.status = 'active'
    AND e.model = 'gemini-embedding-2'
    AND (p.updated_at IS NULL OR e.source_updated_at >= p.updated_at)
  ORDER BY e.embedding OPERATOR(extensions.<=>) query_embedding
  LIMIT LEAST(GREATEST(coalesce(result_limit, 20), 1), 100);
$$;

REVOKE ALL ON FUNCTION public.search_product_discovery_embeddings(
  extensions.vector, uuid, integer
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_product_discovery_embeddings(
  extensions.vector, uuid, integer
) TO anon, authenticated;
