-- Grant authenticator membership LAST, after the request-scope hook was
-- installed, activated, and reloaded by
-- 20260805113000_restore_gigl_tracking_postgrest_capability. PostgreSQL
-- exposes a new membership at commit while PostgREST reloads
-- configuration asynchronously, so activating the hook in this same
-- transaction would leave a post-commit window where an issued worker JWT
-- could invoke PUBLIC-granted RPCs without the five-path restriction.
-- With enforcement predating usability, the token is already confined the
-- moment this membership makes it assumable. Never move this grant to an
-- earlier migration, where a later failure would leave the token
-- unconfined, and never reinstall the hook here.
GRANT gigl_tracking_worker TO authenticator;
