import { BRAND, RADIUS, SPACING, TYPOGRAPHY } from '@/constants/Colors';
import { WALLET_COLORS } from './wallet.colors';

const COMPACT_PADDING_Y = 6;
const DISABLED_BALANCE_OPACITY = 0.6;

export const walletHeroStyles = {
  walletHero: {
    marginHorizontal: SPACING.md,
    marginTop: 0,
    borderRadius: 28,
    padding: SPACING.md,
    backgroundColor: '#191919',
    borderWidth: 1,
    borderColor: '#303030',
  },
  walletHeroHeader: {
    minHeight: 48,
    flexWrap: 'wrap',
    gap: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  walletHeroTitle: {
    color: WALLET_COLORS.white,
    fontSize: 18,
    fontWeight: TYPOGRAPHY.weight.bold,
  },
  addMoneyButton: {
    marginLeft: 'auto',
    minHeight: 36,
    backgroundColor: BRAND.primary,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    borderRadius: RADIUS.full,
    paddingVertical: COMPACT_PADDING_Y,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: WALLET_COLORS.heroBorder,
  },
  addMoneyButtonText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  balanceLabel: {
    letterSpacing: 1,
    color: WALLET_COLORS.mutedText,
    fontSize: 11,
    fontWeight: TYPOGRAPHY.weight.medium,
  },
  balanceAndAccountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 18,
  },
  balanceBlock: { flex: 1, minWidth: 0 },
  accountUnavailableMessage: {
    color: WALLET_COLORS.mutedText,
    fontSize: 11,
    marginTop: 8,
  },
  balanceAmount: {
    letterSpacing: -1.8,
    color: WALLET_COLORS.white,
    fontSize: 40,
    fontWeight: TYPOGRAPHY.weight.black,
    marginTop: SPACING.sm,
  },
  balanceSummaryRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    gap: 8,
  },
  balanceSummaryCell: {
    minHeight: 82,
    paddingHorizontal: 10,
    paddingVertical: 11,
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#393D43',
    backgroundColor: '#202226',
  },
  balanceSummaryLabel: {
    color: WALLET_COLORS.mutedText,
    fontSize: 10,
    fontWeight: TYPOGRAPHY.weight.medium,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  balanceSummaryValue: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weight.bold,
  },
  loyaltyActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  redeemPill: {
    backgroundColor: '#F8B84C',
    borderRadius: RADIUS.full,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  redeemPillText: {
    color: '#191919',
    fontSize: 8,
    fontWeight: TYPOGRAPHY.weight.bold,
  },
  utilityPillsDivider: {
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: WALLET_COLORS.heroBorder,
  },
  utilityPillsLabel: {
    color: WALLET_COLORS.mutedText,
    fontSize: 10,
    fontWeight: TYPOGRAPHY.weight.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 12,
    marginBottom: 8,
  },
  utilityPillsScroll: {
    flexDirection: 'row',
    gap: SPACING.sm,
    paddingBottom: 2,
  },
  utilityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: RADIUS.full,
    backgroundColor: '#252525',
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  utilityPillText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  loyaltyTierBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: RADIUS.full,
    marginTop: 4,
  },
  loyaltyTierTextCompact: {
    color: WALLET_COLORS.loyaltyTierText,
    fontSize: 9,
    fontWeight: TYPOGRAPHY.weight.bold,
    textTransform: 'uppercase',
  },
  primaryActionRow: {
    marginHorizontal: SPACING.md,
    marginTop: SPACING.md,
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  primaryActionButton: {
    flex: 1,
    minHeight: 58,
    paddingHorizontal: 10,
    borderRadius: 18,
    backgroundColor: BRAND.primary,
    paddingVertical: SPACING.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  primaryActionButtonText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  secondaryActionButton: {
    flex: 1,
    minHeight: 58,
    paddingHorizontal: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: WALLET_COLORS.secondaryBorder,
    backgroundColor: WALLET_COLORS.white,
    paddingVertical: SPACING.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  secondaryActionButtonText: {
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  quickSaveButton: {
    marginHorizontal: SPACING.md,
    marginTop: SPACING.sm,
    borderRadius: RADIUS.xl,
    backgroundColor: WALLET_COLORS.quickSaveBackground,
    paddingVertical: SPACING.sm,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  quickSaveButtonText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  balanceActions: {
    flexDirection: 'row',
    marginTop: SPACING.lg,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: WALLET_COLORS.balanceDivider,
  },
  balanceAction: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
  },
  balanceActionText: {
    color: WALLET_COLORS.white,
    fontSize: TYPOGRAPHY.size.base,
    fontWeight: TYPOGRAPHY.weight.semibold,
  },
  disabledBalanceAction: {
    opacity: DISABLED_BALANCE_OPACITY,
  },
  divider: {
    width: 1,
    backgroundColor: WALLET_COLORS.balanceDivider,
  },
} as const;
