import { jest } from '@jest/globals';
import Colors from '@/constants/Colors';

export function createWalletContentProps() {
  return {
    activeSavingsGoal: {
      contribution_amount: 10000,
      contribution_frequency: 'weekly' as const,
      current_amount: 50000,
      id: 'goal-1',
      maturity_date: '2026-09-30',
      product_condition: 'Used',
      product_image: 'https://cdn.example.com/device.jpg',
      product_variant_label: 'Storage: 256GB',
      source_mode: 'manual' as const,
      status: 'active' as const,
      target_amount: 100000,
      title: 'iPhone 15 Pro',
    },
    canCreateFundingAccount: true,
    colors: Colors.light,
    contentContainerStyle: { paddingBottom: 32, paddingTop: 20 },
    earningsBalance: 125000,
    fundAmount: '',
    fundingAccount: {
      accountName: 'Ogabassey/Jane Doe',
      accountNumber: '1234567890',
      bankName: 'Titan Paystack',
      provider: 'paystack' as const,
    },
    isAddingSavingsContribution: false,
    isCreatingFundingAccount: false,
    isFundPending: false,
    isRedeemPending: false,
    isRefetching: false,
    loyaltyPoints: 2000,
    needsPhone: false,
    onChangeFundAmount: jest.fn(),
    onCreateFundingAccount: jest.fn(),
    onChangeRedeemPoints: jest.fn(),
    onAddSavingsContribution: jest.fn(),
    onChangeSavingsDevice: jest.fn(async () => true),
    onResolveSavingsVariant: jest.fn(async () => true),
    onChangeSavingsContributionAmount: jest.fn(),
    onCloseSavingsProgress: jest.fn(),
    onConfirmFund: jest.fn(),
    onConfirmRedeem: jest.fn(),
    onFundSavingsWallet: jest.fn(),
    onManageCards: jest.fn(),
    onOpenFundPanel: jest.fn(),
    onOpenRedeemPanel: jest.fn(),
    onQuickSave: jest.fn(),
    onRefresh: jest.fn(),
    onResetFund: jest.fn(),
    onResetRedeem: jest.fn(),
    onStartSavings: jest.fn(),
    onSubmitPhone: jest.fn(async () => ({ success: true })),
    redeemPoints: '',
    savingsContributionAmount: '',
    savingsBalance: 35000,
    showFundPanel: false,
    showQuickSave: true,
    showRedeemPanel: false,
    showSavingsProgress: false,
    totalBalance: 160000,
    transactions: [
      {
        amount: 2500.75,
        created_at: '2026-04-21T12:30:00.000Z',
        description: 'Order cashback',
        id: 'tx-1',
        type: 'credit' as const,
      },
    ],
  };
}
