// Shared fixtures for the mark-manual-document-dispatch-started suites.
// Extracted so the main suite stays under the 300-line file limit.

export const row = {
  id: 'outbox-1',
  order_id: 'order-1',
  merchant_id: 'merchant-1',
  claim_owner: 'worker-1',
  event_type: 'manual_order_receipt_ready',
};
export const order = {
  customer_id: 'customer-1',
  customer_email: 'ada@example.com',
  customer_name: 'Ada',
  customer_phone: null,
  recorded_by_user_id: 'staff-1',
  import_job_id: null,
  external_source: null,
  total: 100,
  subtotal: 100,
  shipping_fee: 0,
  tax_amount: 0,
  discount_amount: 0,
  amount_paid: 100,
  currency: 'NGN',
  order_number: 'ORD-1',
  payment_status: 'paid',
  payment_method: 'bank_transfer',
  shipping_status: 'pending',
  invoice_type_code: null,
  invoice_note: null,
  payment_due_date: '2026-10-15',
  payment_terms: 'Net 30',
  buyer_reference: 'BUYER-1',
  firs_irn: 'IRN-1',
  firs_csid: 'CSID-1',
  notes: 'Call first',
  transaction_date: '2026-09-28T09:00:00Z',
  invoice_issue_date: null,
  created_at: '2026-09-30T09:00:00Z',
  shipping_address: { city: 'Lagos', postalCode: '100001' },
  order_items: [
    {
      id: 'item-1',
      name: 'Device',
      quantity: 1,
      price: 100,
      variant_name: null,
      condition: 'new',
      item_description: 'Sealed box',
      assurance_fee: 15000,
      line_id: 3,
      unit_code: 'EA',
      line_extension_amount: 95,
      vat_category_code: 'S',
      vat_rate: 7.5,
      vat_amount: 7.12,
      sellers_item_id: 'SKU-1',
    },
  ],
};
export const taxSubtotals = [
  {
    id: 'tax-2',
    vat_category_code: 'E',
    vat_rate: 0,
    taxable_amount: 50000,
    tax_amount: 0,
    exemption_reason: 'exports',
  },
  {
    id: 'tax-1',
    vat_category_code: 'S',
    vat_rate: 7.5,
    taxable_amount: 100000,
    tax_amount: 7500,
    exemption_reason: null,
  },
];
export const transactions = [
  {
    id: 'txn-2',
    amount: 50000,
    created_at: '2026-09-30T09:00:00+00:00',
    description: 'balance',
    metadata: null,
  },
  {
    id: 'txn-1',
    amount: 50000,
    created_at: '2026-09-29T09:00:00+00:00',
    description: null,
    metadata: {
      payment_method: 'bank_transfer',
      webhook_id: 'wh_enrichment_ignored',
    },
  },
];
export const payment = {
  merchantBankCode: '058',
  merchantBankAccountNumber: '1234567890',
  merchantBankName: 'GTBank',
  merchantBankAccountName: 'Shop Ltd',
  virtualAccountNumber: '9990001111',
  virtualAccountBankName: 'Paystack-Titan',
  virtualAccountName: 'Shop Ltd/ORD',
};

export const merchant = {
  businessName: 'Shop Ltd',
  legalEntityName: 'Shop Ltd',
  businessAddress: '1 Market St',
  registeredAddress: null,
  cacRcNumber: 'RC123',
  taxIdentificationNumber: 'TIN123',
  vatRegistrationStatus: 'registered',
  vatRate: 7.5,
  supportEmail: 'support@shop.example.com',
  supportPhone: '+2348000000001',
  phone: '+2348000000002',
  slug: 'shop',
  emailSenderName: null,
  logoUrl: null,
  brandColors: null,
};
